### ISSUE TITLE
when i giving the commmand python3 SocialFish.py it giving down error please help

### ISSUE THREAD

**Issue by souviksenapati** [UndeadSec/SocialFish#107]
Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ModuleNotFoundError: No module named 'flask'

**Comment by A1S0N** [comment]
Try the setup instructions https://github.com/UndeadSec/SocialFish/wiki
