### ISSUE TITLE
An answer.

### ISSUE THREAD

**Issue by kabsss1** [UndeadSec/SocialFish#111]
Hi!

Lost my app key by clothing install terminal. where i can find it?? don't see any log file.

trying this python3 SocialFish.py

get this --> ./SocialFish user password

trying this trying this python3 SocialFish.py *login* *password*

get this --> Traceback (most recent call last):
  File "SocialFish.py", line 537, in <module>
    main()
  File "SocialFish.py", line 529, in main
    head()
  File "/root/SocialFish/core/view.py", line 22, in head
    ''')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 280-286: ordinal not in range(128)

Thanks.

If i use only *password*

get this --> Traceback (most recent call last):
  File "SocialFish.py", line 27, in <module>
    users = {argv[1]: {'password': argv[2]}}
IndexError: list index out of range

**Comment by A1S0N** [comment]
Hi,
Tell us please the python3 version you are running on your machine. 

python3 --version would be enough to get this info.

**Comment by kabsss1** [comment]
python3 --version
Python 3.6.8

**Comment by A1S0N** [comment]
Change the function "head()" in core/view.py , delete the ascii code and try again.

I.E:
def head():
    print("SOCIALFISH")

**Comment by kabsss1** [comment]
got this

./SocialFish user password

**Comment by kabsss1** [comment]
what kind of login password i need to use SF ??
in what file i must put them ?

**Comment by A1S0N** [comment]
You must insert one password and one login to signin in dashboard.

IE:

`python3 SocialFish.py kabsss1 secretpassw`

**Comment by kabsss1** [comment]
awww
i stupid

Thanks a lot, problem solved :)

**Comment by amin825** [comment]
guys i need a solution the probblem is not solved for me yt.
