### ISSUE TITLE
is it possible to make it check the entered password ?

### ISSUE THREAD

**Issue by minanagehsalalma** [UndeadSec/SocialFish#112]
so if the password is correct it accepts it .... and if it's wrong it says the entered password is wrong .. and asks for the password again  .. just like what the real sites do :)

**Comment by A1S0N** [comment]
Good suggestion :D

**Comment by minanagehsalalma** [comment]
@A1S0N   thanks :)

**Comment by minanagehsalalma** [comment]
@A1S0N  i think this may help you 

https://github.com/kgretzky/evilginx2/issues/261

**Comment by kumaark7** [comment]
> so if the password is correct it accepts it .... and if it's wrong it says the entered password is wrong .. and asks for the password again .. just like what the real sites do :)


if you know the right y you try phishing LOL

**Comment by minanagehsalalma** [comment]
> > so if the password is correct it accepts it .... and if it's wrong it says the entered password is wrong .. and asks for the password again .. just like what the real sites do :)
> 
> if you know the right y you try phishing LOL

da fuck did you just say ?!!!!!!.... can you validate the shit server side against the shitty what you have captured !?

**Comment by minanagehsalalma** [comment]
Fixed or not?
