### ISSUE TITLE
QR Code Generation Broken

### ISSUE THREAD

**Issue by thehappydinoa** [UndeadSec/SocialFish#114]
Before you submit this bug report check that you have run the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**
QR Code is never regenerated even after token revoke. This prevents the easy setup feature from working in the mobile app.

**To Reproduce**
1. Try to use QR Code
2. Get invalid token error
3. Look at token 
4. Realize it is not changing at all...
5. Lie down and cry

**Expected behavior**
I wish to be able to use the QR Code for setup.

**Screenshots**
![qrcode-issue](https://user-images.githubusercontent.com/30162978/54485802-dbe2ba80-4855-11e9-8386-76802639fead.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4
 - Browser: Google Chrome
 - Version: sharkNet

**Smartphone (please complete the following information):**
 - Device: PH1
 - OS: Android Pie
 - Browser: SocialFish
 - Version: 1.0

**Comment by A1S0N** [comment]
Hello, you found a bug. Thanks by reporting to us. We'll work on that soon.

**Comment by shovalsh** [comment]
I have created a PR, 
https://github.com/UndeadSec/SocialFish/pull/158
