### ISSUE TITLE
No module named 'secrets'

### ISSUE THREAD

**Issue by Z33DD** [UndeadSec/SocialFish#115]
I followed the instructions correctly, including:
```
python3 -m pip install -r requirements.txt --user
```
But...

```bash
user@Matrix:~/Programs/SocialFish$ python3 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 7, in <module>
    from core.dbsf import initDB
  File "/home/user/Programs/SocialFish/core/dbsf.py", line 3, in <module>
    from core.genToken import genToken, genQRCode
  File "/home/user/Programs/SocialFish/core/genToken.py", line 1, in <module>
    import secrets
ImportError: No module named 'secrets'
```

You're saying the secrets module isn't installed.

**You will try to install manually:**

```bash
user@Matrix:~/Programs/SocialFish$ pip install secrets --user
Collecting secrets
  Could not find a version that satisfies the requirement secrets (from versions: )
No matching distribution found for secrets
```

The python-secrets' [official  @documentation](https://python-secrets.readthedocs.io/en/latest/) has it installed as follows:
```bash
python3 -m pip install python_secrets
```

Still does not work

**Desktop:**
 - OS: [Linux Elementary OS 0.4.1 Loki, Built on "Ubuntu 16.04.5 LTS"]
 - Python Version [Python 3.5.2]
 - Pip Version [pip 19.0.3]

**Comment by unexpectedBy** [comment]
PREREQUISITES to run:

Python 3.6 or >

**Comment by A1S0N** [comment]
Hello,
Please upgrade your python version to a compatible one.

**Comment by ashwathhalemane** [comment]
i am running secrets on python version 3.10.6, still i am facing the same issue.
