### ISSUE TITLE
ImportError: No module named core.config

### ISSUE THREAD

**Issue by megusta63** [UndeadSec/SocialFish#117]
hello!

i try to run this on a mac os mojave 10.14.2
i preinstalled python3 and homebrew.

after running socialfish.py i get this error message:

Traceback (most recent call last):
  File "socialfish.py", line 3, in <module>
    from core.config import *
ImportError: No module named core.config

i took a look in the SocialFish folder, there i see a *core folder with config.py file in it. but i cant find an core.config file.

thanks for your help

**Comment by A1S0N** [comment]
Did you tried to clone again?

**Comment by HamzaKHIATE** [comment]
Hi i had the same issu, try to use python3

**Comment by Johnson1997** [comment]
I install python3 but its giving me same issue like that, any help?

**Comment by Johnson1997** [comment]
when I tried to use sudo pip install python.py,its giving another issue that "could not install packages due to an environmentErro 404 client "
"not found https://pypi.org/simple/python.py

**Comment by sh1va73** [comment]
I have the same issue, did you find a solution?
