### ISSUE TITLE
You have not yet set up an attack vector

### ISSUE THREAD

**Issue by cymilad** [UndeadSec/SocialFish#118]
You have not yet set up an attack vector

![Capture](https://user-images.githubusercontent.com/22496001/54526976-ba84ea00-498d-11e9-91ba-c59fb8c9587c.PNG)

**Comment by Dexvar** [comment]
Did you access the dashboard and clone a website yet?

**Comment by A1S0N** [comment]
*FACEPALM.

**Comment by miladzero** [comment]
> Did you access the dashboard and clone a website yet?

Yes

**Comment by A1S0N** [comment]
Access http://0.0.0.0:5000/neptune

**Comment by ostes** [comment]
and after that   what about clone a web similar to github

**Comment by bcoded200** [comment]
please how do i set up an attack vector.

**Comment by PinkDev1** [comment]
> 
> 
> Access http://0.0.0.0:5000/neptune

Then that's a mistake on the docs, as the docs don't ever mention having to go there

**Comment by jareddarkweb** [comment]
I can access http://0.0.0.0:5000/neptune ...?
