### ISSUE TITLE
Just question no issue at all. 

### ISSUE THREAD

**Issue by doobiesnackin** [UndeadSec/SocialFish#121]
First and foremost, I really enjoy the new setup and dashboard, beautifully created and well done; but, would there be anyway to implement ngrok like before? I tried to simply change the localhost address to an ngrok address given, but sadly it didn’t work. Nonetheless, absolutely cool idea for the app, if only Apple wasn’t such a bitch when adding such applications to the AppStore. Awesome work, loving it!

**Comment by A1S0N** [comment]
Ngrok limits the transfer rate and views, because of that is impossible to it works with ngrok's free version, alternatively you can try the ngrok's paid version :(
