### ISSUE TITLE
Non-ASCII charector in file socialfish.py  on line 144

### ISSUE THREAD

**Issue by praveeni23** [UndeadSec/SocialFish#123]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by A1S0N** [comment]
Please try again, the problem is fixed.
