### ISSUE TITLE
No module named core.config

### ISSUE THREAD

**Issue by MarcoD1337** [UndeadSec/SocialFish#126]
When I run the python file i get hit with the following error

`Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from core.config import *
ImportError: No module named core.config`

**Comment by Dexvar** [comment]
Did you install the requirements?

**Comment by rishabhgupta03** [comment]
yes

**Comment by tiagojpavan** [comment]
Hi, I have the same problem here, but with a little difference on the error message:
Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from core.config import *
ImportError: No module named core.config

I've installed it on the /OPT folder with root rights. Maybe it's the "root" of my problem? Theres a right place to install it? Thanks in advance.

**Comment by GMigiakis** [comment]
Hi i have the same problem when i write 

``python SocialFish.py``
![prob](https://user-images.githubusercontent.com/48793714/56923632-b8a55f00-6ad3-11e9-8aa1-9abb41b8ff37.png)

**Comment by tiagojpavan** [comment]
> Hi i have the same problem
> 
> `python SocialFish.py`
> ![prob](https://user-images.githubusercontent.com/48793714/56923632-b8a55f00-6ad3-11e9-8aa1-9abb41b8ff37.png)

Man, I`ve found something, if you start using "python3 SocialFish.py" instead of "python SocialFish.py", this error wont appear. Well, at last for me this solved the problem.

**Comment by SysHub** [comment]
Hi,
Dis you solve this ? i have the same issue:
I tried with python and python3 and issue still getting:
with python
![image](https://user-images.githubusercontent.com/17937580/59985081-69b80980-95ec-11e9-968b-854da3001bf6.png)
with python3
![image](https://user-images.githubusercontent.com/17937580/59985117-b865a380-95ec-11e9-85d4-991ba1b7e1cc.png)
Previously installed all requirements: (requiriment.txt)
![image](https://user-images.githubusercontent.com/17937580/59985142-ef3bb980-95ec-11e9-9feb-966bab86281f.png)

I appreciate your reply.

**Comment by sokutonyassin** [comment]
i have really failed to get the solution to the same problem can someone please help me out with that us

**Comment by Napster-Nightshade** [comment]
Same issue, can't get it to work either.
Changing it to the previous Version did it for me, but I don't that either now.
I guess it's the installation Directories of the Dependencies which is causing the problem most probably.
Any Help is Appreciated.

**Comment by Napster-Nightshade** [comment]
I got it to work Finally.
The Problem was with the version of pip.
Uninstall the Python 2.7 Version of pip.
-->sudo apt remove python-pip
-->sudo apt install python3-pip
-->sudo pip3 install -r requirements.txt
Good to go.
Please let me know if this doesn't Work for anyone.

**Comment by sh1va73** [comment]
I still have the same issue.

**Comment by saeidtakboy73** [comment]
Hi.
Why error????

Traceback (most recent call last):                  File "SocialFish.py", line 4, in <module>           from core.config import *                     ImportError: No module named core.config

**Comment by sh1va73** [comment]
Same error. I tried the solutions given here, but it did not help.

**Comment by Likhithlpu** [comment]
The Same Issue

**Comment by galatgovardhan** [comment]
Same problam

**Comment by Nawazish55** [comment]
Use 
~/socialfish#python3 SocialFish.py root pass
and your problem is resolved.

**Comment by blackmake** [comment]
Hi
