### ISSUE TITLE
Can this work on Fedora 29 and Python 3?

### ISSUE THREAD

**Issue by xzj8b3** [UndeadSec/SocialFish#127]
Can this work on Fedora 29 and Python 3?

**Comment by xzj8b3** [comment]
_posixsubprocess.c:16:10: fatal error: Python.h: File o directory non esistente
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-k6f4MP/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-OoF7K8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-k6f4MP/subprocess32/

**Comment by emchoko** [comment]
same issue here

**Comment by emchoko** [comment]
Try running:
`dnf install python-devel`
`dnf install python-subprocess32`

Worked for me!
