### ISSUE TITLE
Problems !

### ISSUE THREAD

**Issue by ZICO1985** [UndeadSec/SocialFish#128]
I have two Problems 
![1](https://user-images.githubusercontent.com/48862101/54881573-a2abdb00-4e51-11e9-8be6-fc0d7ca1793b.JPG)
![2](https://user-images.githubusercontent.com/48862101/54881574-a3447180-4e51-11e9-9920-9ab82b91d1ea.JPG)

**Comment by tboss12310** [comment]
same I  dont know whats going on

**Comment by Dexvar** [comment]
The first pic isn't a problem in itself, you should access the dashboard and once you clone the website it shouldn't appear anymore.

The second image, though, never happened to me and can't seem to replicate it.
Does it still happen if you browse using 127.0.0.1?

**Comment by TheFatCow** [comment]
http://0.0.0.0:5000/neptune

After going on the above link social fish on termux Gives this :

[05/May/2019 10:28:19] "GET /creds HTTP/1.1" 200 -

What does this mean
