### ISSUE TITLE
SovialFish problems

### ISSUE THREAD

**Issue by giulio234** [UndeadSec/SocialFish#129]
what should I do if this comes up: ./SocialFish user password

**Comment by Dexvar** [comment]
The user and password are parameters you have to enter while executing SocialFish.py

Check attached image.

![SocialFish](https://user-images.githubusercontent.com/25438090/55000500-f4c83a00-4fd2-11e9-929a-caa84e0a16df.png)

**Comment by A1S0N** [comment]
@Dexvar said it all
