### ISSUE TITLE
macOS error

### ISSUE THREAD

**Issue by g33xter** [UndeadSec/SocialFish#13]
Hi, I know you haven't tested this app on macOS, but I was trying it on macOS Sierra & faced two problems 

1) bundled ngrok was not compatible so, I switched that binary file with official ngrok (from their website), it worked & I didn't get the ngrok error.
2) After that, I'm facing this error now. Is it possible to solve?
![screen shot 2018-02-08 at 05 16 49](https://user-images.githubusercontent.com/8503135/35974979-01f7341a-0c90-11e8-96f7-ee844769a7ef.png)

**Comment by A1S0N** [comment]
Please try to clone now

**Comment by g33xter** [comment]
I tried it, but it spitting the error "You are not authorized to use this tool", on macOS & Kali Linux.

**Comment by adiranas** [comment]
i'm running macOS and i only get that when, of course, I answer no to the question "Do you agree to use this tool for educational purposes only?"
