### ISSUE TITLE
cloning problem

### ISSUE THREAD

**Issue by rishabhgupta03** [UndeadSec/SocialFish#130]
while entering the cloning site and redirecting site of instagram the page is just showing the logo of instagram instead of login credentials but other sites like facebook are successfully loading credentials.

**Comment by A1S0N** [comment]
Please send us a better description of the problem

**Comment by rishabhgupta03** [comment]
while cloning i entered the cloning site as https://www.instagram.com and
directing site to a insta account..after that clicking on the link a blank
white page with a small instagram logo was loading instead of login page to
enter credentials but this was not a case with facebook...it was
successfully cloned with social fish.
