### ISSUE TITLE
Traceback (most recent call last):   File "SocialFish.py", line 3, in <module>     from core.config import * ImportError: No module named core.config

### ISSUE THREAD

**Issue by kennedyvance** [UndeadSec/SocialFish#131]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kennedyvance** [comment]
im experiencing the same issue when running the "python SocialFish.py" command

**Comment by rootBANG** [comment]
I'm getting the samething.

**Comment by IamFadedGamer** [comment]
Having the same issue. Downloaded today

**Comment by tiagojpavan** [comment]
Hi, I have the same issue here:

    Traceback (most recent call last):
    File "SocialFish.py", line 3, in
    from core.config import *
    ImportError: No module named core.config

I've installed it on the /OPT folder with root rights. Maybe it's the "root" of my problem? All requirements have been installed correctly with only these two error messages:

    Found existing installation: requests 2.21.0
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
    Found existing installation: colorama 0.3.7
    Not uninstalling colorama at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'colorama'. No files were found to uninstall.

Theres a right place to install it? Thanks in advance.

**Comment by MohammadBinAftab** [comment]
I am also getting the same issue

**Comment by MohammadBinAftab** [comment]
> Hi, I have the same issue here:
> Traceback (most recent call last):
> File "SocialFish.py", line 3, in
> from core.config import *
> ImportError: No module named core.config
> 
> I've installed it on the /OPT folder with root rights. Maybe it's the "root" of my problem? All requirements have been installed correctly with only these two error messages:
> Found existing installation: requests 2.21.0
> Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
> Can't uninstall 'requests'. No files were found to uninstall.
> Found existing installation: colorama 0.3.7
> Not uninstalling colorama at /usr/lib/python3/dist-packages, outside environment /usr
> Can't uninstall 'colorama'. No files were found to uninstall.
> 
> Theres a right place to install it? Thanks in advance.
> EDIT: Oooook, I've found the "root" of my problem. Using "python3 SocialFish.py" instead of "python SocialFish.py" solved my initial problem. A little distraction from me. Sorry. 👍 



> Hi, I have the same issue here:
> Traceback (most recent call last):
> File "SocialFish.py", line 3, in
> from core.config import *
> ImportError: No module named core.config
> 
> I've installed it on the /OPT folder with root rights. Maybe it's the "root" of my problem? All requirements have been installed correctly with only these two error messages:
> Found existing installation: requests 2.21.0
> Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
> Can't uninstall 'requests'. No files were found to uninstall.
> Found existing installation: colorama 0.3.7
> Not uninstalling colorama at /usr/lib/python3/dist-packages, outside environment /usr
> Can't uninstall 'colorama'. No files were found to uninstall.
> 
> Theres a right place to install it? Thanks in advance.
> EDIT: Oooook, I've found the "root" of my problem. Using "python3 SocialFish.py" instead of "python SocialFish.py" solved my initial problem. A little distraction from me. Sorry. :/

please tell me.How you fix it ?? 
I am getting the same issue as you get.

**Comment by tiagojpavan** [comment]
> please tell me.How you fix it ??
> I am getting the same issue as you get.

Im my comment theres the solution. Start the aplication from bash using python3. If you try to start using python, you will get the same error.

bash>> python SocialFish.py   <-- leads you to the error, because SF use python3 instead of python.
bash>> python3 SocialFish.py <-- correct command to start SF.

Hope this help you. Good luck.

**Comment by MohammadBinAftab** [comment]
> please tell me.How you fix it ??
> I am getting the same issue as you get.
> 
> Im my comment theres the solution. Start the aplication from bash using python3. If you try to start using python, you will get the same error.
> bash>> python SocialFish.py   <-- leads you to the error, because SF use python3 instead of python.
> bash>> python3 SocialFish.py <-- correct command to start SF.
> Hope this help you. Good luck.

now i am getting error of no module named "Flask".
But I have already downloaded flask .
this is in line 2 error.

**Comment by tiagojpavan** [comment]
> > please tell me.How you fix it ??
> > I am getting the same issue as you get.
> > Im my comment theres the solution. Start the aplication from bash using python3. If you try to start using python, you will get the same error.
> > bash>> python SocialFish.py   <-- leads you to the error, because SF use python3 instead of python.
> > bash>> python3 SocialFish.py <-- correct command to start SF.
> > Hope this help you. Good luck.
> 
> now i am getting error of no module named "Flask".
> But I have already downloaded flask .
> this is in line 2 error.

Sorry, but as I dont get this error here, dont know how to help in this situation. :/

**Comment by SysHub** [comment]
Hello,

I posted same issue... can you help me?
https://github.com/UndeadSec/SocialFish/issues/126#issuecomment-504808432

**Comment by oristotel** [comment]
Running `sudo pip3 install -r requirements.txt` instead of `sudo pip install -r requirements.txt` and after that `python3 SocialFish.py` solved this problem for me

**Comment by PjDev09** [comment]
Thanks Bro alot solved my problem!!!

**Comment by Namig09** [comment]
Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ModuleNotFoundError: No module named 'core.config'
Help me please! I enter Python SocialFish.py and gives this error from above

**Comment by Namig09** [comment]
Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ModuleNotFoundError: No module named 'core.config'
Help me please! I enter Python SocialFish.py and gives this error from above

**Comment by sundaysec** [comment]
Update to latest python3 (3.8 worked for me 3.5 didn't work) version then 
`pip3 install -r requirement.txt`

**Comment by hwac121** [comment]
Kali 2020
ImportError: No module named core.config
Used: pip3 install -r requirements.txt
Ran: python3 SocialFish.py
still no joy.... still getting same error. ANY help to solve this is appreciated. This works perfectly on Parrot Security OS for me, just not on this install of Kali 2020.

**Comment by sh1va73** [comment]
Same error on fresh Kali 2020:
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ModuleNotFoundError: No module named 'core.config'

**Comment by sh1va73** [comment]
I finally found solution. Go to /core folder and add:` __init__.py` file.
Then problem solved.

**Comment by Likhithlpu** [comment]
Same Issue

**Comment by Likhithlpu** [comment]
i am getting this error
Traceback (most recent call last):
  File "SocialFish.py", line 5, in <module>
    from core.view import head
  File "/home/kali/SocialFish/core/view.py", line 11
SyntaxError: Non-ASCII character '\xe2' in file /home/kali/SocialFish/core/view.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by angel951127** [comment]
ImportError: No module named flask
root@kali:~/Escritorio/SocialFish# ^C
root@kali:~/Escritorio/SocialFish# python3 SocialFish.py
Traceback (most recent call last):
  File "/root/Escritorio/SocialFish/SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ModuleNotFoundError: No module named 'flask'

**Comment by lestat1898** [comment]
Same problem here, I've updated pip, pip3, python, I have the __init__.py file and it simply doesn't work in termux neither terminal. 
Have you found any solution?

**Comment by Shaheertura** [comment]
@truesamurai it works thanks so much @lestat1898 add double __ 
cd SocialFish
cd core
touch __init__.py
cd ..
python3 SocialFish.py {usernameofyourcomputer} {passwordofyourcomputer}
