### ISSUE TITLE
./socialfish user password ?? 

### ISSUE THREAD

**Issue by elofort23** [UndeadSec/SocialFish#132]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by A1S0N** [comment]
View [https://github.com/UndeadSec/SocialFish/issues/129](https://github.com/UndeadSec/SocialFish/issues/129)

**Comment by wassim180605** [comment]
$ python3 SocialFish.py ./SocialFish <NAME OF COMPUTER> <PASSWORD OF COMPUTER>

**Comment by wassim180605** [comment]
python3 SocialFish.py ./SocialFish {name of computer} {password of computer}

**Comment by SnowBrez** [comment]
@wassim180605 same probleme ... help pleassse

**Comment by wassim180605** [comment]
I know how to fix itjust type this “python3 SocialFish.py {name of computer} {password of computer}, then you go to http://0.0.0.0/neptune type in name of computer and name of password and you’re in.

**Comment by akelindtstrom** [comment]
Why it starts but there is no menu? and it seems to be loading for like a eternity. The logo is there but the only command that works is Ctrl c to exit

**Comment by kinghacking48** [comment]
IndexError: list index out of range

**Comment by primelord253** [comment]
when i go to the duplicate login page it just says /login/login /login/ over and over again

**Comment by arjunmaurya1** [comment]
> python3 SocialFish.py ./SocialFish {name of computer} {password of computer}

Same issue
