### ISSUE TITLE
./SocialFish user password !! how can I fix it ??

### ISSUE THREAD

**Issue by sou200** [UndeadSec/SocialFish#133]

**Comment by A1S0N** [comment]
python3 SocialFish.py youruser yourpassword

**Comment by A1S0N** [comment]
View [](https://github.com/UndeadSec/SocialFish/issues/129)

**Comment by A1S0N** [comment]
View [https://github.com/UndeadSec/SocialFish/issues/129](https://github.com/UndeadSec/SocialFish/issues/129)

**Comment by Pranay1004** [comment]
type python3 SocialFish..py root toor
