### ISSUE TITLE
Https in SF

### ISSUE THREAD

**Issue by uviman** [UndeadSec/SocialFish#136]
as far as I remember, the 2-nd edition of SF worked via https, now it with http? why is it such way or maybe I have installed not correctly?

**Comment by A1S0N** [comment]
The 2-nd edition uses Ngrok for tunneling the app, now you must to configure by yourself as you want to, you still can use Https, just need to make it works with that. But to make it native is a good idea for the next updates.

**Comment by uviman** [comment]
is it possible to return to 2-d version? or how to establish with third one?
