### ISSUE TITLE
Allowing to email without authentication

### ISSUE THREAD

**Issue by Dexvar** [UndeadSec/SocialFish#137]
As far as I know, there are ways to send emails using python without requiring a real email account or even without authentication.

Are there plans to make email authentication optional or non-necessary in future versions in the send mail feature?

**Comment by A1S0N** [comment]
How to send a mail without an email account/provider?

**Comment by Dexvar** [comment]
Sorry, I might be mistaken but I recall using the following script long ago in order to email from inexistent email addresses:

`import smtplib

sender="SenderAddr@SenderDomain"
receivers=["ReceiverAddr@ReceiverDomain"]

message = """From: SenderName <SenderAddr@SenderDomain>
To: ReceiverName <ReceiverAddr@ReceiverDomain>
MIME-Version: 1.0
Content-type: text/html
Subject: SubjectGoesHere


"""

smtpObj = smtplib.SMTP('SMTPServerHere')
smtpObj.sendmail(sender, receivers, message)         
try:
	print("Successfully sent email")
except:
	print("Unable to send email")
` 

The only thing I would need back when I used it was an open SMTP relay.
