### ISSUE TITLE
http://0.0.0.0:5000/neptune

### ISSUE THREAD

**Issue by wassim180605** [UndeadSec/SocialFish#139]
I'm getting a link on Socialfish where I need to go to http://0.0.0.0:5000/neptune and fill in a username and a password, but if I just fill in my kali linux username and password there will come a pop-up with ''Bad''.

What do I have to do??

**Comment by Dexvar** [comment]
You don't have to fill in your kali linux username and password.

You have to fill in the username and passwords you used while executing SocialFish.py

![SocialFish](https://user-images.githubusercontent.com/25438090/55947366-9c3da180-5c4e-11e9-88e2-0327c9ee05a0.png)

For instance, as shown in the image I attached, the credentials would be:

Username: admin
Password: password

**Comment by wassim180605** [comment]
I stil get the pop-up “bad”

**Comment by wassim180605** [comment]
root@kali:~# cd Bureaublad/SocialFish
root@kali:~/Bureaublad/SocialFish# python3 SocialFish.py ./SocialFish root kali


                          '
                        '   '  UNDEADSEC | t.me/UndeadSec 
                      '       '  youtube.com/c/UndeadSec - BRAZIL
                 .  '  .        '                        '
             '             '      '                   '   '
  ███████ ████████ ███████ ██ ███████ ██       ███████ ██ ███████ ██   ██ 
  ██      ██    ██ ██      ██ ██   ██ ██       ██      ██ ██      ██   ██ 
  ███████ ██    ██ ██      ██ ███████ ██       █████   ██ ███████ ███████ 
       ██ ██    ██ ██      ██ ██   ██ ██       ██      ██      ██ ██   ██ 
  ███████ ████████ ███████ ██ ██   ██ ███████  ██      ██ ███████ ██   ██ 
      .    '   '....'               ..'.      ' .
         '  .                     .     '          '     '  v3.0Nepture
               '  .  .  .  .  . '.    .'              '  .
                   '         '    '. '      Twitter: https://twitter.com/A1S0N_
                     '       '      '       Site: https://www.undeadsec.com
                       ' .  '
                           
Go to http://0.0.0.0:5000/neptune to start
 * Serving Flask app "SocialFish" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Apr/2019 02:25:58] "GET /neptune HTTP/1.1" 200 -
127.0.0.1 - - [11/Apr/2019 02:26:06] "POST /neptune HTTP/1.1" 200 -
    
this is what i got, i didnt know how to screenshot in mac so i copied everything

**Comment by A1S0N** [comment]
Go to `http://0.0.0.0:5000/neptune`

**Comment by wassim180605** [comment]
That’s the problem, if I’m going to http://0.0.0.0/neptune and login I will get a pop up with “bad” on it. So what are the login username and password?

**Comment by Foxengton** [comment]
Try 127.0.0.1:5000/neptune.

**Comment by morrocash** [comment]
Same problem , after login : Bad ????

**Comment by 426344** [comment]
Is linux is necessary for socialfishing ?

**Comment by darkoit** [comment]
same problem

**Comment by Nobs23** [comment]
Having the same problem

**Comment by saugatsn** [comment]
How do I create a link to send the URL to the victim outside internal network?

**Comment by 51200** [comment]
Having the same problem

**Comment by Chakroot** [comment]
> That’s the problem, if I’m going to http://0.0.0.0/neptune and login I will get a pop up with “bad” on it. So what are the login username and password?

I have the same problem as you solved it

**Comment by Ansh2411** [comment]
> I'm getting a link on Socialfish where I need to go to http://0.0.0.0:5000/neptune and fill in a username and a password, but if I just fill in my kali linux username and password there will come a pop-up with ''Bad''.
> 
> 
> 
> What do I have to do??

Reply-
You do not have to fill your kali linux id and pw
You have to fill username as "username" and password as "password"

**Comment by Mardiasa** [comment]
https://0.0.0.0:5000/neptune i was get it but i can't to login whit the link socialfish what must can i do please?

**Comment by krvikrantsingh51** [comment]
> Try http://127.0.0.1:5000/neptune.

it works

**Comment by Uyuzbarmen** [comment]
Arkadaşlar socialfish uygulamasında server ve token verebilecek varmı
