### ISSUE TITLE
http://0.0.0.0:5000/neptune

### ISSUE THREAD

**Issue by Larrss** [UndeadSec/SocialFish#140]
"This sight can't be reached" on chrome, on a desktop, running windows. Wrong browser or am I dumb, haven't gone into fishing much so I'm a tad new but it seems interesting.

**Comment by A1S0N** [comment]
I can't help you with this info, tell me more about the problem.

**Comment by Dexvar** [comment]
> "This sight can't be reached" on chrome, on a desktop, running windows. Wrong browser or am I dumb, haven't gone into fishing much so I'm a tad new but it seems interesting.

Are you connecting from the computer SocialFish is running?

**Comment by Foxengton** [comment]
http://127.0.0.1:5000/neptune

**Comment by TechnicSmile** [comment]
Am also having the same issue, for some reason i cannot accesses it.

**Comment by 426344** [comment]
Is linux is necessary for socialfishing ?

**Comment by halil-polat205** [comment]
When I run http://127.0.0.1:5000/neptune it says this to me too:
Use a production WSGI server instead

**Comment by halil-polat205** [comment]
> Is linux is necessary for socialfishing ?

No , linux is not necessary for socialfishing.You can also make it from termux.
