### ISSUE TITLE
can i use for External Network ?

### ISSUE THREAD

**Issue by azizaashiq** [UndeadSec/SocialFish#141]
Hi Every One,

Sorry but i have a question , how can I create Attack link for external network 0.0.0.0:5000 this is working on Local network only , then how can i use ?

**Comment by A1S0N** [comment]
Yes you can, just configure your server to run on WAN.  Alternatively you can use Ngrok(paid version only).

**Comment by deadfishhackers** [comment]
Yeah port forwarding @azizaashiq 

<hr>
<p align="center"><img src="http://i68.tinypic.com/1z57t5e.png"></p>

**Comment by sandippshah** [comment]
How can run on
 http://localhost:5000 ?

**Comment by sandippshah** [comment]
?
