### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by bLoodypRince** [UndeadSec/SocialFish#146]
Hey I am using Parrot OS version 4.19.0-parrot4-28t-amd64
whenever i try to run SocialFIsh it shows this error

$sudo python3 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 5, in <module>
    from core.scansf import nScan
  File "/home/sam/Desktop/SocialFish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'

**Comment by A1S0N** [comment]
Did you already ran `pip3 install -r requirements.txt` ?

If the answer is YES, you must to try the following:

`python3 -m pip uninstall nmap`

`python3 -m pip install python-nmap`
