### ISSUE TITLE
Facing Problems please Answer and help.

### ISSUE THREAD

**Issue by Abrar-Faiyaz** [UndeadSec/SocialFish#148]
'
                        '   '  UNDEADSEC | t.me/UndeadSec
                      '       '  youtube.com/c/UndeadSec - BRAZIL
                 .  '  .        '                        '
             '             '      '                   '   '
  ███████ ████████ ███████ ██ ███████ ██       ███████ ██ ███████ ██   ██
  ██      ██    ██ ██      ██ ██   ██ ██       ██      ██ ██      ██   ██
  ███████ ██    ██ ██      ██ ███████ ██       █████   ██ ███████ ███████
       ██ ██    ██ ██      ██ ██   ██ ██       ██      ██      ██ ██   ██
  ███████ ████████ ███████ ██ ██   ██ ███████  ██      ██ ███████ ██   ██
      .    '   '....'               ..'.      ' .
         '  .                     .     '          '     '  v3.0Nepture
               '  .  .  .  .  . '.    .'              '  .
                   '         '    '. '      Twitter: https://twitter.com/A1S0N_
                     '       '      '       Site: https://www.undeadsec.com
                       ' .  '

Go to http://0.0.0.0:5000/neptune to start
 * Serving Flask app "SocialFish" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

What should i do now? i can't access to that link which was given.

**Comment by TheFatCow** [comment]
http://0.0.0.0:5000/neptune

After going on the above link social fish on termux Gives this :

[05/May/2019 10:28:19] "GET /creds HTTP/1.1" 200 -

What does this mean

**Comment by TheFatCow** [comment]
Please help

**Comment by A1S0N** [comment]
Duplicated.
Please view https://github.com/UndeadSec/SocialFish/issues/151
