### ISSUE TITLE
Network error. Verify your connection

### ISSUE THREAD

**Issue by kali64amd** [UndeadSec/SocialFish#15]
OS --> Parrot Sec

I'm getting this error so please advise. is this bug? 

Already checked network connection work fine & requirement has been installed.   

 #python SocialFish.py

  ....._____.......     ____ ____ ____ _ ____ _       ____ _ ____ _  _ 
      /     \/|         [__  |  | |    | |__| |       |___ | [__  |__|
      \o__  /\|         ___] |__| |___ | |  | |___    |    | ___] |  |
          \|           
                    [!] Network error. Verify your connection.

**Comment by A1S0N** [comment]
Your connection should be very slow at that time, could you test again now?
If doesn't work, try to comment this lines:

`if connected() == False:
     print '''
  ....._____.......     ____ ____ ____ _ ____ _       ____ _ ____ _  _ 
      /     \/|         [__  |  | |    | |__| |       |___ | [__  |__|
      \o__  /\|         ___] |__| |___ | |  | |___    |    | ___] |  |
          \|           
                    {0}[{1}!{0}]{1} Network error. Verify your connection.\n
'''.format(RED, END)
     exit(0)`

**Comment by kali64amd** [comment]
yup its fixed, Appreciate you'r help.

And Awesome Tool better the SET.

**Comment by fuzail43** [comment]
I have same problem but it's still not fixed

**Comment by fuzail43** [comment]
Is there any solution for this
