### ISSUE TITLE
Problem!!!!

### ISSUE THREAD

**Issue by TheFatCow** [UndeadSec/SocialFish#150]
http://0.0.0.0:5000/neptune

After going on the above link social fish on termux Gives this :

[05/May/2019 10:28:19] "GET /creds HTTP/1.1" 200 -

What does this mean
![Screenshot_2019-05-05-11-09-46](https://user-images.githubusercontent.com/50284597/57189017-64144080-6f26-11e9-9131-18a779533757.png)

**Comment by TheFatCow** [comment]
Help

**Comment by A1S0N** [comment]
It's not an error or something bad, this is a server's log

`[05/May/2019 10:28:19] "GET /creds HTTP/1.1" 200 -` -> **Complete Log**

`[05/May/2019 10:28:19]`  -> **Date Time**

`GET` -> **Method: POST/GET**

`/creds` -> **Path**

`HTTP/1.1` -> **Protocol**

`200` -> **Status Code. i.e. 200 is the okay code.**
