### ISSUE TITLE
Not able to connect to http://0.0.0.0:5000/neptune

### ISSUE THREAD

**Issue by sweeterthanhimn** [UndeadSec/SocialFish#151]
I setup everything with the SocialFish/ But I go to http://0.0.0.0:5000/neptune and it says "This site can’t be reached The webpage at http://0.0.0.0:5000/neptune might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID" Any help?

**Comment by A1S0N** [comment]
Are you trying to access from another device? If the answer is YES, you must replace 0.0.0.0 with your LAN/EXTERNAL IP/DNS. You can see your LAN IP running the command IFCONFIG, it will show you something like this:

> wlp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.1.103  netmask 255.255.255.0  broadcast 192.168.1.255
>         inet6 fe80::5ccb:fd05:f719:8abc  prefixlen 64  scopeid 0x20<link>
>         ether XX:XX:XX:XX:XX:XX  txqueuelen 1000  (Ethernet)
>         RX packets 6658  bytes 6514892 (6.2 MiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 3126  bytes 635516 (620.6 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 

Look at line 2:

**inet 192.168.1.103  netmask 255.255.255.0  broadcast 192.168.1.255**

192.168.1.103 i.e. will be your desired IP.

**Comment by Harley8281** [comment]
I changed 0.0.0.0:5000 to my ip and got a page like this.......
Now what can i do
![20190525_235438](https://user-images.githubusercontent.com/51030999/58373248-8529e900-7f48-11e9-948f-6f3f9fa4bb67.jpg)

**Comment by djurr0** [comment]
Hey, I searched: http://0.0.0.0:5000/neptune and it would come up with the same error. So then i did what you said and wrote: http://myIP.5000/neptune and it brought me to the login in page, and once i entered my username and password, and all that came up was "bad".
![ejd](https://user-images.githubusercontent.com/53464903/62829359-ddff4880-bc3e-11e9-886a-5207c3ad4e09.PNG)

**Comment by GuptaPurujit** [comment]
no issue just type use http://localhost:5000 to open the attack site and to setup which site to phish http://localhost:500/neptune

**Comment by GuptaPurujit** [comment]
Every time you print ctrl+c i.e. you stop the program and restart it you have to redeclare the site to be phished for it to work i.e you have to declare the attack vector again and again
