### ISSUE TITLE
Smartphone dont capture credentials

### ISSUE THREAD

**Issue by aresthunder1** [UndeadSec/SocialFish#152]
Login with smarthphone dont generate credentials

**Comment by aresthunder1** [comment]
is a line that someone types by smartphone

http://login/device-based/login/async/?refsrc=https%3A%2F%2Fpt-br.facebook.com%2F&lwv=100&jio_prefilled=false

**Comment by A1S0N** [comment]
We need more info about your problem :(

Is there any way of you send us a demo, like a screenshot or video?

**Comment by aresthunder1** [comment]
Primeiramente me desculpa péssimo Inglês.

Se não me engano vc é Br, então pode ser em português?

O Phishing não funciona quando você tenta logar a partir de um smarphone, por exemplo quando insiro minha senha e login no facebook e clico "entrar" ele não faz nada, não sai da tela e nem efetua a captura das credenciais.
