### ISSUE TITLE
Traceback (most recent call last):   File "SocialFish.py", line 5, in <module>     from core.scansf import nScan   File "/home/vishnuganesan/Desktop/SocialFish/core/scansf.py", line 1, in <module>     import nmap ModuleNotFoundError: No module named 'nmap'

### ISSUE THREAD

**Issue by vishnuganesan** [UndeadSec/SocialFish#153]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xd20111** [comment]
Same problem do you have any solution?
