### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by silentShodow** [UndeadSec/SocialFish#154]
Sorry. Maybe this question is stupid but I don't know where I give token for SocialFish in Google play

Help me please :)

(Sorry if my English is bad)

**Comment by franklintimoteo** [comment]
Execute socialfish, 
Enter into: http://0.0.0.0:5000/neptune
Insert: user and password
On smartphone : click on icon barcode and scan the barcode in http://0.0.0.0:5000/neptune

**Comment by Patilyash22** [comment]
Where will i get the socialfish token
