### ISSUE TITLE
tunnel link doesnt work if it is opened from msmartphones

### ISSUE THREAD

**Issue by asdfghjkl1996** [UndeadSec/SocialFish#161]
when i send the link to the victim and if he open it from mobile devices, the login page comes in but there is no way to click enter or sign in and it is showing 405 method not allowed in ngrok.
please how do i fix this

**Comment by JrCK** [comment]
Have the same issue here. Running on a Raspberry Pi 4B 4GB. In my case this issue just occur when using external IP. On same network, with 0.0.0.0:5000 IP and port, works pretty well, but this is very limited. Can anyone solve this? Can someone help us?
