### ISSUE TITLE
Not working on Mobile Browsers

### ISSUE THREAD

**Issue by FabLong** [UndeadSec/SocialFish#162]
**Describe the bug**
I have the phising page working correctly when accessed using a desktop browser. It evens works when connecting via a mobile browser (ios safari + android chrome) after selecting request desktop site.

However if i do not request the desktop site on mobile, the page is filled with variations of /login. I checked the index.html file(attached as index.txt) and this also shows /login variations on desktop browsers. Is there anyway to prevent this, could I somehow force the desktop index.html to be read by mobile devices without it being overwritten with the corrupted variation everytime it needs to be loaded by a mobile browser.

[index.txt](https://github.com/UndeadSec/SocialFish/files/3490414/index.txt) 
^^^^^^ This should be a twitter login page.

**To Reproduce**
Open in phising page on a mobile browser.

**Expected behavior**
Load fake twitter login page on mobile browsers.

**Desktop (please complete the following information):**
Running SocialFish on: 
- OS: Windows 10 Home

Thanks

**Comment by rikbjorn** [comment]
im having the same problem

**Comment by Mafi4Boy** [comment]
I think it's an anti phishing method of social networks
