### ISSUE TITLE
python3 SocialFish.py not working

### ISSUE THREAD

**Issue by Sim0nGame** [UndeadSec/SocialFish#165]
I am trying to run but i always get this error code

Traceback (most recent call last):
  File "SocialFish.py", line 2, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash

i correctly install requirements.txt and i try to run pip3 install flask

**Comment by franklintimoteo** [comment]
Hello @Sim0nGame 
try: 
```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python SocialFish.py root pass
```

**Comment by DB2121** [comment]
ERROR: Could not find a version that satisfies the requirement nmap (from versions: none)                                                                           
ERROR: No matching distribution found for nmap

please how can i resolve this issue
