### ISSUE TITLE
LAN URL

### ISSUE THREAD

**Issue by Woogie20** [UndeadSec/SocialFish#166]
Hello, I was hoping someone would please be able to help me. 

I am trying to figure out how to make SocialFish work across my LAN.  As of now, I can only get SocialFish to run via my loopback IP (127.0.0.1) in Kali. As a result, the http://0.0.0.0:5000 URL will only work on my machine; if I send the URL to any other test devices on my LAN it will not work ('Server cannot be located').

Can someone please help me figure out how to configure the program so it will work via my machines LAN IP address? Thank you so much!

**Comment by Cramcon** [comment]
Same mistake, have you found a solution yet?
