### ISSUE TITLE
WAN Link - With Ngrok

### ISSUE THREAD

**Issue by Mougatsu** [UndeadSec/SocialFish#167]
Hello,
I'd like to ask how it is possible to use the link in a WAN connection.

#What I tried:
  *Setting up Ngrok - link is not redirecting (Tried With  Port: 80 
                                                                                         Port: 5000)
  *Tried to Change SocialFish.py: From(0.0.0.0 port:5000) To (Ngrok IP port:80)

Do you have any solution?

Best Regards.

**Comment by sleepingspy999** [comment]
just run ngrok http 5000

All should work correctly

Nothing will work on mobile browsers tho, issue has been raised.

**Comment by RishabhRyber** [comment]
An easy way is to run ngrok http 5000
But this don't work on mobile browsers.

I found a proper tutorial using ngrok :: [https://www.youtube.com/watch?v=fDAHNbTNT9w](https://www.youtube.com/watch?v=fDAHNbTNT9w)
