### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by MrSigmaa** [UndeadSec/SocialFish#169]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

I made sure I have all the requirements installed. Then I specifically tried to install sqlite3 with pip3 but I already have it installed.

After running this command: `python3 SocialFish.py yourcomputer yourpassword
`
I receive the error:

```
Traceback (most recent call last):
  File "SocialFish.py", line 7, in <module>
    from core.dbsf import initDB
  File "/root/Tools/SocialFish/core/dbsf.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by franklintimoteo** [comment]
What's your distro?
try to install: libsqlite3-dev or sqlite-devel

**Comment by MrSigmaa** [comment]
Kali and I tried that. No luck.

**Comment by franklintimoteo** [comment]
@MrSigmaa try, 
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python SocialFish.py root pass

**Comment by MrSigmaa** [comment]
Did that but still get the same error.

**Comment by Nimanth114** [comment]
@franklintimoteo  
did that even though still hetting error
