### ISSUE TITLE
Ubuntu 16.04 /Server/ngrok: not found

### ISSUE THREAD

**Issue by securityhawk** [UndeadSec/SocialFish#17]
Hi Guys

I have installed the prerequisites, SF launches but I get this message:

/Server/ngrok: not found

Does anyone have any pointers?

Thanks

Phil

**Comment by A1S0N** [comment]
Did you installed the requeriments.txt ?
Because there's the download function from wget and need that.

**Comment by adiranas** [comment]
is that the actual directory of the error? coz it's pointing to a root dir /Server/ngrok instead of ./Server/ngrok which has the ngrok if downloaded correctly

**Comment by securityhawk** [comment]
Hi Guys

Thanks for replying, I have installed the requirements.txt and the error is sh: 1: ./Server/ngrok: not found

Any help is appreciated.

Thanks

Phil

**Comment by melophonic** [comment]
Ran into this error; solution was to install unzip: `sudo apt-get install unzip`

**Comment by A1S0N** [comment]
Try the new version
