### ISSUE TITLE
Not Capturing Credentials in Mobile Browser

### ISSUE THREAD

**Issue by harbinc** [UndeadSec/SocialFish#175]
I have the latest version of SF installed. Starts with no issues and captures credentials when using my desktop browser. If I go to the same page on my Android the page loads but does not capture credentials or redirect when hitting submit. Any thoughts?

"POST /login/device-based/login/async/?refsrc=https%3A%2F%2Fm.facebook.com%2F&lwv=100 HTTP/1.1" 405 -

**Comment by aresthunder1** [comment]
same problem!

**Comment by rikbjorn** [comment]
Im having the same problem T^T

**Comment by Miloudi-Imad** [comment]
for me it doesn't capture credentials only when i fill both the email and the password input ...

**Comment by jeanettsaraneali** [comment]
Has someone found a solution?

**Comment by nox2213** [comment]
I habe the same Problem. I tried different mobile browsers, all have the same reaction: no redirect, no capture.

**Comment by 9-9-1-1** [comment]
> I have the latest version of SF installed. Starts with no issues and captures credentials when using my desktop browser. If I go to the same page on my Android the page loads but does not capture credentials or redirect when hitting submit. Any thoughts?
> 
> "POST /login/device-based/login/async/?refsrc=https%3A%2F%[2Fm.facebook.com](http://2Fm.facebook.com)%2F&lwv=100 HTTP/1.1" 405 -
