### ISSUE TITLE
When I open the webpage it says, "It Works". 

### ISSUE THREAD

**Issue by notannon** [UndeadSec/SocialFish#18]
When I open the page it says, "it works" and not a fishing site.

**Comment by A1S0N** [comment]
Verify if you have another service running in port 80.

**Comment by notannon** [comment]
I used nmap and it said the apache server was running correctly.

**Comment by g33xter** [comment]
@notannon Which OS you are running this on?

**Comment by notannon** [comment]
I fixed it, their was already an apache server running on port 80. So if I had more than 1 link open the second one just said it works. Im on MacOS.
