### ISSUE TITLE
attack url problem

### ISSUE THREAD

**Issue by rmarimo** [UndeadSec/SocialFish#180]
after I enter the web I want to clone and get the link, after clicking the link it only shows a blank page and it says "This site can’t be reachedThe webpage at http://0.0.0.0:5000/ might be temporarily down or it may have moved permanently to a new web address." 

what do I do?

**Comment by sleepingspy999** [comment]
have you logged in and set your attack vector yet ?
 http://0.0.0.0:5000/neptune

**Comment by MinntFM** [comment]
> have you logged in and set your attack vector yet ? http://0.0.0.0:5000/neptune

it doesnt even let you onto the site
