### ISSUE TITLE
Custom page not capturing credentials 

### ISSUE THREAD

**Issue by EdC0st4** [UndeadSec/SocialFish#181]
It is just me? Also im having trouble capturing creds from a specific website..

**Comment by franklintimoteo** [comment]
Hello @EdC0st4 what's site?

**Comment by EdC0st4** [comment]
Hi @franklintimoteo,
Thanks for replying, i already figured out how to clone and setup the website for phishing.

When i host the html skeleton it doesent grap username and pass.. (see below)

<html>
<head></head>
<body>
	<form action="/login" method="POST">
	    <label>Email Address</label>
	    <input type="email" name="email" placeholder="Email" autocomplete="off">
	    <label>Password</label>
	    <input type="password" name="password" placeholder="Password" autocomplete="off">
		<button type="submit">sign in</button>                                
	</form>
</body>
</html>

**Comment by franklintimoteo** [comment]
Can you show me any concrete examples?
@EdC0st4
