### ISSUE TITLE
Cant install the tool

### ISSUE THREAD

**Issue by hacker1b** [UndeadSec/SocialFish#182]
Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ModuleNotFoundError: No module named 'flask' 
 What to do, please reply

**Comment by franklintimoteo** [comment]
use: pip install -r requirements.txt

**Comment by annaschmitz2021** [comment]
how can i install from beginning. i have loptop windows 7, and i want to open socialfish with tool, so i was trying for 2 days but i cant do it, can somebody help me please
