### ISSUE TITLE
Error "bad"

### ISSUE THREAD

**Issue by JCluzet** [UndeadSec/SocialFish#184]
Hi, 
I'm on the website with : http://0.0.0.0:5000/neptune

But i don't understand what is login and password ? 
Thanks!

**Comment by jeanettsaraneali** [comment]
./python3 SocialFish.py hereputusername hereputpassword  
change those last 2 options for whatever you want and go to http://0.0.0.0:5000/neptune and use those credentials

**Comment by Nobs23** [comment]
It's not working

**Comment by Nobs23** [comment]
It says bad when I put the password in browser

**Comment by eyxg** [comment]
yeah same

**Comment by Killer141** [comment]
Use google cloud console, worked for me :)
