### ISSUE TITLE
unable to input in to the login form of cloned websites

### ISSUE THREAD

**Issue by jepunband** [UndeadSec/SocialFish#185]
hi i tried testing it on both cloned netflix and wordpress sites, it did not work. For netflix all i'm seeing on the browser are a buch of text login/login/login ..... and for wordpress CSS did not work and i'm unable to input  anything in the login form.

I'm testing it on the SocialFishMobile app. I also opened the cloned page from a desktop browser using the local ip, same results.

facebook seem to display correctly on browser but not capturing credentials and also not redirecting.

**Comment by Kazo78** [comment]
I have the same problem ! did you find the solution?

**Comment by skrking** [comment]
no

**Comment by sleepingspy999** [comment]
Are you trying on mobile browser or desktop cause mobile browser dont work bug raised.Works ok on desktop browsers tho.
