### ISSUE TITLE
/usr/local/bin/python3: No module named pip

### ISSUE THREAD

**Issue by Kazo78** [UndeadSec/SocialFish#187]
Hello when I try to enter this command: python3 -m pip install -r requirements.txt
sa tell me: /usr/local/bin/python3: No module named pip
but yet I have well installed Python 3.8.1 or normally pip is already installed in it so I do not understand. Thank you for your help

root@kali:~# su root
root@kali:~# cd SocialFish
root@kali:~/SocialFish# python3 -m pip install -r requirements.txt
/usr/local/bin/python3: No module named pip
root@kali:~/SocialFish#

**Comment by velocity010** [comment]
sudo apt-get install python3 python3-pip python3-dev -y
