### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by velocity010** [UndeadSec/SocialFish#189]
after putting in the correct website to access: http://0.0.0.0:5000/neptune

I get 

This site can’t be reached
The webpage at http://0.0.0.0:5000/neptune might be temporarily down or it may have moved permanently to a new web address.

ERR_ADDRESS_INVALID

**Comment by Decado01** [comment]
I got the same problem. can anyone help me out?

**Comment by teorailin** [comment]
You need to use a VPN, but i get another error()
The following error was encountered while trying to retrieve the URL: http://0.0.0.0:5000/neptune

Connection to 0.0.0.0 failed.

The system returned: (111) Connection refused

The remote host or network has been down. Please try the request again.

Your cache manager is root.

**Comment by max-sweet** [comment]
I tried using a vpn and I'm still getting the same error, the site is temporarily down or permanently changed address.
