### ISSUE TITLE
No module named 'core.config'

### ISSUE THREAD

**Issue by truesamurai** [UndeadSec/SocialFish#192]
I have installed succesfully and have install all requirements.
But still I get this error on latest Kali Linux:

Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ModuleNotFoundError: No module named 'core.config'

I tried running sudo pip3 install -r requirements.txt instead of sudo pip install -r requirements.txt and after that python3 SocialFish.py, but I have same error.

**Comment by sleepingspy999** [comment]
Which version of python are you running ?
best thing is to create a python3 virtual environment in socialfish directory and install into that.

**Comment by sh1va73** [comment]
I am using Python3. I will try out your suggestion with virtual env. Thanks.

**Comment by banderaroja81** [comment]
> Which version of python are you running ?
> best thing is to create a python3 virtual environment in socialfish directory and install into that.

Hello There. Im A Noob here, can u please explain how to do what u r saying?

**Comment by hwac121** [comment]
All I know is I REALLY wish someone would fix this error. Great piece of software until it was broken...

**Comment by sh1va73** [comment]
I never found a soltution for the error , but I installed a fresh Kali installation and reinstalled SocialFish again. Now it's working again.

**Comment by sh1va73** [comment]
I am confused: on my laptop it works , on my desktop i get error: no module named core.config
Same python version, same pip version. I tried with virtualenv but got same error.

**Comment by sh1va73** [comment]
I finally found solution. Go to /core folder and add: __init__.py file.
Then problem solved.
