### ISSUE TITLE
Not Generating link

### ISSUE THREAD

**Issue by nyawpawgithub** [UndeadSec/SocialFish#193]
![Screenshot_20200305_175912_com termux](https://user-images.githubusercontent.com/61817554/75970509-6743d880-5f0b-11ea-926d-8afd36d2fe7f.jpg)

NotWorking? Help

**Comment by git-blip** [comment]
Same problem

**Comment by termuxqueen** [comment]
> ![Screenshot_20200305_175912_com termux](https://user-images.githubusercontent.com/61817554/75970509-6743d880-5f0b-11ea-926d-8afd36d2fe7f.jpg)
> 
> NotWorking? Help

Just turn on Hotspot before generating link.

Termux Queen 
Youtuber...
