### ISSUE TITLE
Question: ¿How to get facebook password?

### ISSUE THREAD

**Issue by jsandovalc** [UndeadSec/SocialFish#198]
Hi everyone, thanks for the great job.

I have a question. I cloned the facebook login page and tested. The password is not stored. Apparently, facebook hashes or does something to the password client side. ¿Is there an easy way to fix this?.

The only "fix" I think is creating a custom template based on the fake one, or dynamically fixing the template to just send the form data.

Testing with github, the password is stored without problem.

Thanks again.

**Comment by manuelinfosec** [comment]
True. How did you solve problem.?

**Comment by manuelinfosec** [comment]
It worked.  But I had to use desktop view. Wow.
