### ISSUE TITLE
No module named 'nmap'

### ISSUE THREAD

**Issue by DPIDorP** [UndeadSec/SocialFish#199]
I'm running Kali Linux 2018.1 on Virtual Box 6.1.6
Here is error code:
root@kali:~/socialfish# python3 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 6, in <module>
    from core.scansf import nScan
  File "/root/socialfish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'
tell me if you need anymore info.
please help if there is any way, thanks.

**Comment by moekme93** [comment]
> 
> 
> I'm running Kali Linux 2018.1 on Virtual Box 6.1.6
> Here is error code:
> root@kali:~/socialfish# python3 SocialFish.py
> Traceback (most recent call last):
> File "SocialFish.py", line 6, in
> from core.scansf import nScan
> File "/root/socialfish/core/scansf.py", line 1, in
> import nmap
> ModuleNotFoundError: No module named 'nmap'
> tell me if you need anymore info.
> please help if there is any way, thanks.

This is a common error for anyone using Oracle VM VirtualBox, I don't personally know if you can fix it.

**Comment by moekme93** [comment]
Make sure to install nmap:
sudo apt-get update && sudo apt-get install nmap

And all the Python modules:
sudo -H pip3 install -r requirements.txt and it should work, I loaded my VirtualBox just to test this for you and it works

**Comment by Redoxahmii** [comment]
> Make sure to install nmap:
> sudo apt-get update && sudo apt-get install nmap
> 
> And all the Python modules:
> sudo -H pip3 install -r requirements.txt and it should work, I loaded my VirtualBox just to test this for you and it works

im having the same issue and i have checked already to see if it is installed or not and it clearly is. Any solutions?

**Comment by sk3ptikul** [comment]
Edit requirements.txt and change python-nmap  to python3-nmap

**Comment by MARCELLUS1488** [comment]
> sudo -H pip3 install -r requirements.txt

Thanks, it worked for me
