### ISSUE TITLE
Using paid version of ngrok to have dedicated domain names on the links (server) generated by the ngrok program

### ISSUE THREAD

**Issue by JAD1932** [UndeadSec/SocialFish#20]
Can we do it?

**Comment by A1S0N** [comment]
Yes, I will work on that :D

**Comment by aimlee** [comment]
@A1S0N , Hi, bro, thank you for your wonderful product, but there is such a problem, Can you please tell me that how can i fix that? 
![screenshot from 2018-08-27 09-58-34](https://user-images.githubusercontent.com/35259280/44639910-52b28600-a9e0-11e8-94b2-281530727d94.png)

**Comment by gentle2hack** [comment]
Thanks so much for the good workCan you amend Blackeye so that its listening session stays open to receive more hack detail.

 I notice once a detail is captures  ... the listening session end immediately

Kind assists
Thansk
gentle2hack@gmail.com
