### ISSUE TITLE
flask need help frinds kindly help 

### ISSUE THREAD

**Issue by samirhayat** [UndeadSec/SocialFish#200]
root@kali:~/SocialFish# ls
CODE_OF_CONDUCT.md  CONTIBUTING.md  core  images  __init__.py  LICENSE  README.md  requirements.txt  SocialFish.py  templates
root@kali:~/SocialFish# python3 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ModuleNotFoundError: No module named 'flask'

**Comment by SpookyPatrick** [comment]
try to install requirements by running this command line :
.
python3 -m pip install -r requirements.txt
.
if it says pip not installed then you should install pip by running : 
.
sudo apt install python3-pip

**Comment by samirhayat** [comment]
SpookyPatrick brother it says all requirements are satisafied so whats the issue

**Comment by SpookyPatrick** [comment]
what is the command are you running to start SocialFish.
if you are running it with sudo, try to run it without.

**Comment by samirhayat** [comment]
SpookyPatrick brother i tried  the both python3 and python but still not working thanks brother
i also tried to run it with suso and without sudo but not working waiting for the developer to answer
