### ISSUE TITLE
it gives me this 

### ISSUE THREAD

**Issue by excep** [UndeadSec/SocialFish#203]
Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ImportError: No module named core.config

**Comment by annaschmitz2021** [comment]
how can i install from beginning. i have loptop windows 7, and i want to open socialfish with tool, so i was trying for 2 days but i cant do it, can somebody help me please

**Comment by hwac121** [comment]
> how can i install from beginning. i have loptop windows 7, and i want to open socialfish with tool, so i was trying for 2 days but i cant do it, can somebody help me please

You need bash on LINUX, this is not for MS Windows. Not to mention, if you have no idea what you are doing on a LINUX system yet, you have no business installing something like this, or installing anything at all until you learn how to use LINUX.

**Comment by hwac121** [comment]
ImportError: No module named core.config

Still getting this error, and I have seen no effort to fix it yet which is VERY upsetting. This is a great app, even did a brief tutorial on it on my youtube channel for Parrot Security OS. Now though it just breaks on both Kali and Parrot Security. I would love to see this working again...

**Comment by sh1va73** [comment]
I have same error. On my laptop it works fine, but on my desktop I have this error. Both are same version installations.

**Comment by sh1va73** [comment]
I finally found solution. Go to /core folder and add: __init__.py file.
Then problem solved.

**Comment by hwac121** [comment]
sh1va73 - AWESOME! Worked thx!
