### ISSUE TITLE
shows error "This site can't be reached" on http://0.0.0.0:5000/neptune

### ISSUE THREAD

**Issue by njpromethium** [UndeadSec/SocialFish#206]
Shows no error in the terminal. But when I try to open the url It doesn't work. Gives error "ERR_ADDRESS_INVALID"
![image](https://user-images.githubusercontent.com/48097551/82117632-16feb780-9793-11ea-98a3-0786290500c2.png)
![image](https://user-images.githubusercontent.com/48097551/82117637-241ba680-9793-11ea-87f8-63015ec8b85e.png)

**Comment by justinbalaguer** [comment]
I have the same issue. Have you got it working?

**Comment by NajibAhmed** [comment]
@justinbalaguer unfortunately no. But I've found a similar alternative, [zphisher](https://github.com/htr-tech/zphisher).

**Comment by j-dogcoder** [comment]
also having this issue.

**Comment by j-dogcoder** [comment]
Also in issue #245

**Comment by PrivyetCyka** [comment]
Same here...was working perfectly fine yesterday now it won't connect
