### ISSUE TITLE
no module named core.config

### ISSUE THREAD

**Issue by truesamurai** [UndeadSec/SocialFish#214]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

when i start SocialFish I get an error: 

sudo python3 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 4, in <module>
    from core.config import *
ModuleNotFoundError: No module named 'core.config'

I cant find much info about this error. what does the error core.config mean?

**To Reproduce**
1. sudo python3 SocialFish.py
> all requirements are satisfied

**Expected behavior**
normal start of tool

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Kali 2020.2
 - Browser [e.g. chrome, safari] Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sh1va73** [comment]
I finally found solution. Go to /core folder and add: __init__.py file.
Then problem solved.
