### ISSUE TITLE
no module named 'nmap' 

### ISSUE THREAD

**Issue by Forbesgriffin** [UndeadSec/SocialFish#219]
Traceback (most recent call last):
  File "SocialFish.py", line 6, in <module>
    from core.scansf import nScan
  File "/home/kali/SocialFish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'

P.S i've installed all requirements

**Comment by checolatecosmico** [comment]
checolate@kali:~/hack/SocialFish$ sudo python3 SocialFish.py 
Traceback (most recent call last):
  File "SocialFish.py", line 6, in <module>
    from core.scansf import nScan
  File "/home/checolate/hack/SocialFish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'

**Comment by checolatecosmico** [comment]
> Traceback (most recent call last):
> File "SocialFish.py", line 6, in
> from core.scansf import nScan
> File "/home/kali/SocialFish/core/scansf.py", line 1, in
> import nmap
> ModuleNotFoundError: No module named 'nmap'
> 
> P.S i've installed all requirements

&&&&&&

I try this:
$ python Socialfish.py username password

and run!

**Comment by frankiehathaway** [comment]
python3 -m pip install -r requirements.txt               - try that it works perfectly
