### ISSUE TITLE
Creating new sites 

### ISSUE THREAD

**Issue by MrOgieBogie** [UndeadSec/SocialFish#22]
Is it possible to create your own custom sites in http?

**Comment by dardano** [comment]
That would be a real nice thing to have the option to create custom sites.

**Comment by A1S0N** [comment]
Yes, I will work on that :D

**Comment by ming123245** [comment]
please add to the list VK ***vk.com***

**Comment by ming123245** [comment]
please add to the list VK vk.com and https://www.icloud.com/ for APPLE
