### ISSUE TITLE
Tolong Di Perbaiki

### ISSUE THREAD

**Issue by PikiAbdulAzis55** [UndeadSec/SocialFish#223]
Tolong Kalau Bisa Penginstalan Nya Lewat Termux Juga,Dan Mohon Buat Tutorial Nya...
:+1: 

Eroor Ini Karena Menginstall Di Apk Termux

Tapi Saya Tak Bisa Menjalankan
 Nya

Eroor :

Disaat Saya Menjalankan Nya Dengan Perintah
"python2 SocialFish.py"

Terdapat Eroor Seperti Ini : 

python2 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ImportError: No module named flask

Eroor : 

Disaat Saya Menjalankan Nya Dengan Perintah
"python SocialFish.py"

Terdapat Eroor Seperti Ini : 

Traceback (most recent call last):
  File "SocialFish.py", line 5, in <module>
    from core.view import head
  File "/data/data/com.termux/files/home/SocialFish/core/view.py", line 1, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

Disaat Saya Menjalankan Nya Dengan Perintah
"python3 SocialFish.py"

Terdapat Eroor Seperti Ini :

Traceback (most recent call last):
  File "SocialFish.py", line 5, in <module>
    from core.view import head
  File "/data/data/com.termux/files/home/SocialFish/core/view.py", line 1, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

Disaat Saya Menjalankan Nya Dengan Perintah
"pip2 install -r requirements.txt"

Eroor Ini Di Terakhir Ketika Penginstalan Sudah Terinstall...

Seperti Ini : 

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting requests==2.20.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl
Collecting PyLaTeX==1.3.0 (from -r requirements.txt (line 2))
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pylatex/
  Using cached https://files.pythonhosted.org/packages/2d/cb/ed0447fb99ed73d6fd823aa6a43eff9bd06081e566d6043a9d1930a4dfd6/PyLaTeX-1.3.0.tar.gz
Collecting python-nmap (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/dc/f2/9e1a2953d4d824e183ac033e3d223055e40e695fa6db2cb3e94a864eaa84/python-nmap-0.6.1.tar.gz
Collecting qrcode==6.1 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/42/87/4a3a77e59ab7493d64da1f69bf1c2e899a4cf81e51b2baa855e8cc8115be/qrcode-6.1-py2.py3-none-any.whl
Collecting Flask==1.0.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl
Collecting colorama==0.4.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting Flask_Login==0.4.1 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz
Collecting nmap==0.0.1 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/33/65/1bb09cc9532e75d84890d2b3c96be812fd6076fbc3c8ed4e5531abd4898f/nmap-0.0.1.tar.gz
Collecting python-secrets (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/bf/8c/76cc642fe1f1692729b16a6ed212ae5e97c38cebf58f4125f28133d20d6e/python_secrets-18.11.5-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests==2.20.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests==2.20.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.20.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.20.0->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting ordered-set (from PyLaTeX==1.3.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a3/b7/d4d69641cbe707a45c23b190f2d717466ba5accc4c70b5f7a8a450387895/ordered-set-3.1.1.tar.gz
Collecting future>=0.15.2 (from PyLaTeX==1.3.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting six (from qrcode==6.1->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from Flask==1.0.2->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting click>=5.1 (from Flask==1.0.2->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from Flask==1.0.2->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask==1.0.2->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting yamlreader (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/84/4b/3af5480c26b3235dcd0984b9664b48115c2308c8c4f22e7162322be4ec0f/yamlreader-3.0.4.tar.gz
Collecting Pygments (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl
Collecting sphinx (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7d/66/a4af242b4348b729b9d46ce5db23943ce9bca7da9bbe2ece60dc27f26420/Sphinx-1.8.5-py2.py3-none-any.whl
Collecting tox (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/9d/4d/bdd9d9a1ad56713d4b92c66f606811d6c580835d20728ae96140bfbab5f5/tox-3.18.1-py2.py3-none-any.whl
Collecting numpy (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/b7/6f/24647f014eef9b67a24adfcbcd4f4928349b4a0f8393b3d7fe648d4d2de3/numpy-1.16.6.zip
Collecting gnupg (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/96/6c/21f99b450d2f0821ff35343b9a7843b71e98de35192454606435c72991a8/gnupg-2.3.1.tar.gz
Collecting lxml (from python-secrets->-r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/2c/4d/3ec1ea8512a7fbf57f02dee3035e2cce2d63d0e9c0ab8e4e376e01452597/lxml-4.5.2.tar.gz

"EROOR KETIKA PENGINSTALAN SUDAH TERINSTALL"
Terdapat Eroor Seperti Ini : 

ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-QaCZqk/lxml/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-QaCZqk/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-QaCZqk/lxml/
    Complete output (3 lines):
    Building lxml version 4.5.2.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Disaat Saya Menjalankan Nya Dengan Perintah
"python3 -m pip install -r requirements.txt"

Terdapat Eroor Yg Sama...

**Comment by filatah** [comment]
sudo apt-get install libxml2-dev and libxslt-dev and sudo python3-m pip install cython numpy

**Comment by jhod668** [comment]
Could not build wheels for numpy which use PEP 517 and cannot be installed directly
