### ISSUE TITLE
create some costume site

### ISSUE THREAD

**Issue by christmex** [UndeadSec/SocialFish#23]
how to create some costume site . please help

**Comment by An0nUD4Y** [comment]
Try this one  https://github.com/An0nUD4Y/SocialFish 

you will find more sites....

And i will also add some costume sites their.

**Comment by Aegis66** [comment]
Hello, could you create a http://twitch.tv/login fishing page?

**Comment by usama7628674** [comment]
@Aegis66 Here is the PR for twitch https://github.com/An0nUD4Y/SocialFish/pull/11.
