### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by hayaletadmin** [UndeadSec/SocialFish#232]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SO-KEi** [comment]
Hi! What's up?

**Comment by majid786786** [comment]
Yes
