### ISSUE TITLE
Am new to this I want install sudo 

### ISSUE THREAD

**Issue by chibsah1988** [UndeadSec/SocialFish#233]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hwac121** [comment]
Then go learn about sudo. This specific application has nothing to do with using or installing sudo!! In fact you should not even be messing with stuff like this until you actually LEARN LINUX!

**Comment by chibsah1988** [comment]
Am opening on android

**Comment by chibsah1988** [comment]
Everything works but can't get victims details

**Comment by hwac121** [comment]
There ya go, that's more specific thank you. =)
So, the first thing I would try is to reconnect the android app to the computer app using the ID number given in the main app. I set the main app up on my server so then I can use it remotely with android in hand for example.

**Comment by SO-KEi** [comment]
message troperwillis@tutanota.com He is a very good hacker and he knows more about the socialfish and d rest.
 
 
  On Mon, Oct 5, 2020 at 1:43 AM, chibsah1988<notifications@github.com> wrote:   


Everything works but can't get victims details
