### ISSUE TITLE
After victims login the password and username name don't show it give me link and I don't how to the the details  please I need help 

### ISSUE THREAD

**Issue by chibsah1988** [UndeadSec/SocialFish#236]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JustVladKaz** [comment]
Leave solution here: https://github.com/UndeadSec/SocialFish/issues/278#issuecomment-840444976
