### ISSUE TITLE
i am not getting the site it is telling closed ..

### ISSUE THREAD

**Issue by pok-star** [UndeadSec/SocialFish#239]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by max-sweet** [comment]
same problem for me, says the site is temporarily down or permanently changed web address

**Comment by isaac-easie** [comment]
It's o

**Comment by pray4mercyx** [comment]
is there a fix for it now?
