### ISSUE TITLE
NVM FIXED [Please Delete this, Thanks]

### ISSUE THREAD

**Issue by noammiz007** [UndeadSec/SocialFish#26]
nvm fixed

**Comment by Deniero** [comment]
https://www.youtube.com/watch?v=hwMPsHkrS0M
watch this tutorial

**Comment by Deniero** [comment]
you need to install the programms in requirements.txt first

**Comment by noammiz007** [comment]
I already installed the requirements

**Comment by noammiz007** [comment]
and i already saw this tutorial

**Comment by xhimanshuz** [comment]
`pip install wget`

**Comment by noammiz007** [comment]
i already install the pip install wget

**Comment by noammiz007** [comment]
please help me

**Comment by xhimanshuz** [comment]
What Error?
