### ISSUE TITLE
after installing everything, when using the link, i get "you have not yet set up an attack vendor".

### ISSUE THREAD

**Issue by Ezhurino** [UndeadSec/SocialFish#265]
the link works, the installation was smooth but did i miss something? it's up and running but this is what i get
![Capture](https://user-images.githubusercontent.com/76562252/103094196-fdf99700-45fc-11eb-9fad-c5b27dfb1f78.JPG)

**Comment by krzysko** [comment]
"Go to http://0.0.0.0:5000/neptune to start"

**Comment by Ezhurino** [comment]
> "Go to http://0.0.0.0:5000/neptune to start"

yeah but the site's down for some reason
![image](https://user-images.githubusercontent.com/76562252/103138425-cfe68680-46d2-11eb-97e7-5c5da6531fb8.png)

**Comment by ljw416** [comment]
0.0.0.0 is an invalid IP address, you should use the real IP address instead

**Comment by TheNameIsAz** [comment]
You should try http://localhost:5000/neptune (or http://127.0.0.1/neptune)

![issues#265](https://user-images.githubusercontent.com/59475962/103402434-6bea1500-4b4d-11eb-8fa7-11e55eb5d64c.png)

**Comment by mukul679** [comment]
Which user name and password we should entered it's kali machine or something else
