### ISSUE TITLE
Netflix and more websites bug

### ISSUE THREAD

**Issue by PangwenE** [UndeadSec/SocialFish#270]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**
not displaying page correctly
**To Reproduce**
1. Select "netflix.com/login" as your link, and whatever u want as ur redirect
2. Click on the lightning
3. Attempt to Navigate to the website.
4. glitchiness intesnfies

**Expected behavior**
me being able to see a proper view of the website

**Screenshots**
![image](https://user-images.githubusercontent.com/46404863/108407818-1808bd80-71d9-11eb-9839-15a18db4cdaf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows for browser and kali linux for the fishing software]
 - Browser [e.g. brave, firefox]
 - Version [latest since making this]

**Additional context**

**Comment by jollran2005** [comment]
I have same problem

**Comment by s7612f** [comment]
I have the same problem
