### ISSUE TITLE
LINK IS NOT DISPLAY 

### ISSUE THREAD

**Issue by Djalok8260** [UndeadSec/SocialFish#271]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Doesn't display the link 
![Screenshot_2021-02-19-19-21-49](https://user-images.githubusercontent.com/74955280/108513053-0d891980-72e8-11eb-92e2-dfe052af8fa2.png)
**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lithium-codes** [comment]
make the ngrok server manually

**Comment by Piratno1** [comment]
> make the ngrok server manually

How to make it manual?

**Comment by Andre24706** [comment]
why if i use a the ngrok optio it doesn't work ad it always send me the same link? (that  don't work)

**Comment by Mo1384** [comment]
سلام خوبین
