### ISSUE TITLE
How can I resolve phishing detection for facebook.

### ISSUE THREAD

**Issue by AayushZ** [UndeadSec/SocialFish#272]
Since the css in facebook site was not working in social phish , I copied the original html of facebook and copy pasted it . I modified the code to use the login.php script provided by social phish. I hosted it in 000webhost.com then ran it . I got the login info but the page gets detected as phishing .  I read a few articles and found that there are specific strings in the page that allows the browser to detect is as phishing . Is there any way i can prevent the page from getting detected ?

**Comment by GitLuckyStrike** [comment]
how did you host it over internet i'm getting 0.0.0.0 ip i can't even open it on my phone !!

**Comment by eZh3lp** [comment]
> how did you host it over internet i'm getting 0.0.0.0 ip i can't even open it on my phone !!

- open SocialPhish.py with you preferred text editor
- search for "5000" it will bring you to:
 # Inicia o banco
        initDB(DATABASE)
        app.run(host="0.0.0.0", port=5000)

- change host to your IP

Be aware that the displayed urls in the dashboard aren't updated so if you change IP or Port you will need to open the URL according to your changes...

**Comment by GitLuckyStrike** [comment]
Thanks
