### ISSUE TITLE
HELP ME! while typing python SocialFish.py then showing this traceback (most recent call last):   File "SocialFish.py", line 3, in <module>     from flask import Flask, request, render_template, jsonify, redirect, g, flash ImportError: No module named flask

### ISSUE THREAD

**Issue by Sahilcrockroaz** [UndeadSec/SocialFish#274]

**Comment by eZh3lp** [comment]
"no module named Flask" - did you follow the installation instructions and installed the requirements before running?
if yes try:
python3 -m pip install Flask
if no follow:
https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish

**Comment by JustVladKaz** [comment]
Solution:
`python3 -m pip install Flask`
`python3 SocialFish.py`
