### ISSUE TITLE
*SocialFish - kali linux*  send this link to the victim : No link......please help!

### ISSUE THREAD

**Issue by AY04AL003** [UndeadSec/SocialFish#276]

**Comment by AY04AL003** [comment]
![404](https://user-images.githubusercontent.com/74264613/112054705-2d656480-8b56-11eb-9bac-918c6215fd1a.JPG)

**Comment by Phone-Metal** [comment]
@AY04AL003
Does the tinyurl link work or not tho ?

**Comment by AY04AL003** [comment]
> @AY04AL003
> Does the tinyurl link work or not tho ?

Now it works

**Comment by qcd20430xcoxccom** [comment]
I am getting the same error. But my tinyurl link also isn't working

**Comment by qcd20430xcoxccom** [comment]
> I am getting the same error. But my tinyurl link also isn't working

Please help me resolve the error
