### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by borshYT** [UndeadSec/SocialFish#277]
./SocialFish <youruser> <yourpassword>

i.e.: ./SocialFish.py root pass

How to fix it?
Linux Mint

**Comment by eZh3lp** [comment]
python3 SocialFish.py root pass

**Comment by Afnan011** [comment]
> ./SocialFish
> 
> i.e.: ./SocialFish.py root pass
> 
> How to fix it?
> Linux Mint

python3 SocialFish <youruser> <yourpassword>
