### ISSUE TITLE
Username & password

### ISSUE THREAD

**Issue by aswathparves** [UndeadSec/SocialFish#280]
What is the username & password for Social fish its not coming.....plz help me![Screenshot_20210415-151430.jpg](https://user-images.githubusercontent.com/61221663/114849366-4b448300-9dfd-11eb-919b-2138d2b6ff0e.jpg)

What should I do...I'm using in termux in mobile

**Comment by jollran2005** [comment]
By default the username is: youruser & password is:yourpassword

**Comment by abbasi1377** [comment]
termux

**Comment by abbasi1377** [comment]
> What is the username & password for Social fish its not coming.....plz help me![Screenshot_20210415-151430.jpg](https://user-images.githubusercontent.com/61221663/114849366-4b448300-9dfd-11eb-919b-2138d2b6ff0e.jpg)
> 
> What should I do...I'm using in termux in mobile

**Comment by jollran2005** [comment]
Oh, you don’t need the account information for socialfish. You need your
root password to run the command as root
