### ISSUE TITLE
I have setup all thing but can't understan how toi use and appy 

### ISSUE THREAD

**Issue by shekharP1536** [UndeadSec/SocialFish#282]
Runing on Window 10 
and using VSCode
Also help how to get api 
![image](https://user-images.githubusercontent.com/83689949/117102244-8e0ed080-ad95-11eb-828d-a8db106abea1.png)

**Comment by JustVladKaz** [comment]
Leave solution here: https://github.com/UndeadSec/SocialFish/issues/278#issuecomment-840444976
