### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by sbloodborne** [UndeadSec/SocialFish#283]
Please help! Can anyone try and describe in more detail how the installation works? I tried reading up online and did some research but still have to no idea how to install this on my mac. I have downloaded github desktop and as far as i can tell i have managed to clone social fish but then not sure how to proceed. Do I enter the same in the command box? Please just try to explain step by step with more detail.

I would appreciate it.!

**Comment by sbloodborne** [comment]
never mind. i figured it out. however! getting the password from the victim doesnt seem to be working. i tested it on myself. i get the email but pass doesnt show up. any ideas?

**Comment by sbloodborne** [comment]
btw its for facebook

**Comment by JustVladKaz** [comment]
Leave solution here: https://github.com/UndeadSec/SocialFish/issues/278#issuecomment-840444976
