### ISSUE TITLE
termux

### ISSUE THREAD

**Issue by saedee** [UndeadSec/SocialFish#285]
termux

_Originally posted by @abbasi1377 in https://github.com/UndeadSec/SocialFish/issues/280#issuecomment-853334732_

**Comment by abbasi1377** [comment]
> termux
> 
> _Originally posted by @abbasi1377 in [#280 (comment)](https://github.com/UndeadSec/SocialFish/issues/280#issuecomment-853334732)_

**Comment by saedee** [comment]
@ #
Duplicate of #
