### ISSUE TITLE
The Attack URL Not Opening

### ISSUE THREAD

**Issue by VictoryPlayZx90** [UndeadSec/SocialFish#287]
![image](https://user-images.githubusercontent.com/79135460/121809692-699ef180-cc7b-11eb-9604-7d252833d98a.png)

the attack url ain't opening for me
also the main Neptune is opening on 192.168.1.10:5000 not 0.0.0.0:5000
(im a literal beginner to hacking)

**Comment by kash6699** [comment]
same problem I'm even getting a blank page sometimes
![Screenshot from 2021-06-17 12-41-46](https://user-images.githubusercontent.com/86042952/122349056-77998e80-cf69-11eb-8447-22636a50370f.png)

**Comment by busigor0110** [comment]
do u find how to use url

**Comment by kash6699** [comment]
It doesn't get generated after choosing ngrok
