### ISSUE TITLE
saeede.fallahi@yahoo.com

### ISSUE THREAD

**Issue by saedee** [UndeadSec/SocialFish#289]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Usearname: sar.2817

**Comment by abbasi1377** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
>

**Comment by saedee** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 

usearname : saedee_f1

**Comment by saedee** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> usearname : @masoudabbasi92

**Comment by saedee** [comment]
> > > **Is your feature request related to a problem? Please describe.**
> > > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > > **Describe the solution you'd like**
> > > A clear and concise description of what you want to happen.
> > > **Describe alternatives you've considered**
> > > A clear and concise description of any alternative solutions or features you've considered.
> > > **Additional context**
> > > Add any other context or screenshots about the feature request here.
> > > usearname : @masoudabbasi92

**Comment by saedee** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 

usearname : @masoudabbasi92

**Comment by saedee** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > 
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen.
> > 
> > **Describe alternatives you've considered**
> > A clear and concise description of any alternative solutions or features you've considered.
> > 
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> > usearname : @masoudabbasi92
> 
> 

usearname : @masoudabbasi92

**Comment by saedee** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 

usearname : @masoudabbasi92

**Comment by saedee** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > 
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen.
> > 
> > **Describe alternatives you've considered**
> > A clear and concise description of any alternative solutions or features you've considered.
> > 
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> > 
> 
> usearname : @masoudabbasi92

**Comment by saedee** [comment]
> > > **Is your feature request related to a problem? Please describe.**
> > > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > > 
> > > **Describe the solution you'd like**
> > > A clear and concise description of what you want to happen.
> > > 
> > > **Describe alternatives you've considered**
> > > A clear and concise description of any alternative solutions or features you've considered.
> > > 
> > > **Additional context**
> > > Add any other context or screenshots about the feature request here.
> > > 
> > 
> > usearname : @masoudabbasi92
> 
> 
>

**Comment by saedee** [comment]
> > > > **Is your feature request related to a problem? Please describe.**
> > > > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > > > 
> > > > **Describe the solution you'd like**
> > > > A clear and concise description of what you want to happen.
> > > > 
> > > > **Describe alternatives you've considered**
> > > > A clear and concise description of any alternative solutions or features you've considered.
> > > > 
> > > > **Additional context**
> > > > Add any other context or screenshots about the feature request here.
> > > > 
> > > 
> > > usearname : @masoudabbasi92
> > 
> > 
> > 
> 
>

**Comment by saedee** [comment]
> > > > **Is your feature request related to a problem? Please describe.**
> > > > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > > > 
> > > > **Describe the solution you'd like**
> > > > A clear and concise description of what you want to happen.
> > > > 
> > > > **Describe alternatives you've considered**
> > > > A clear and concise description of any alternative solutions or features you've considered.
> > > > 
> > > > **Additional context**
> > > > Add any other context or screenshots about the feature request here.
> > > > 
> > > 
> > > usearname : @masoudabbasi92
> > 
> > 
> > 
> 
>

**Comment by saedee** [comment]
در تاریخ سه‌شنبه ۲۲ ژوئن ۲۰۲۱،‏ ۱۸:۳۹ saedee ***@***.***>
نوشت:

**Comment by saedee** [comment]
در تاریخ جمعه ۱۸ ژوئن ۲۰۲۱،‏ ۴:۴۳ abbasi1377 ***@***.***>
نوشت:

**Comment by saedee** [comment]
@saedee _f1

**Comment by saedee** [comment]
#292

**Comment by saedee** [comment]
> @saedee _f1
