### ISSUE TITLE
Traceback (most recent call last):   File "SocialFish.py", line 12, in <module>     from wget import download ImportError: No module named wget

### ISSUE THREAD

**Issue by sameer2012** [UndeadSec/SocialFish#29]
Traceback (most recent call last):
  File "SocialFish.py", line 12, in <module>
    from wget import download
ImportError: No module named wget

help!!

**Comment by arescanpolat** [comment]
# pip install wget

**Comment by khawabkashyap** [comment]
from wget import download
ImportError: No module named wget
when i try to do pip install wget 
root@localhost:~# pip install wget
Requirement already satisfied: wget in /usr/local/lib/python3.6/dist-packages (3.2)

**Comment by usama7628674** [comment]
@khawabkashyap It's becuase you're using python3 as default version.To fix it try the following command and reinstall wget `sudo python -m pip install -U --force-reinstall pip`

**Comment by khawabkashyap** [comment]
@usama7628674 
sorry but i was using python 2.7 but then i change it to default 3.6 and then run your given command after reinstall wget 
it said sucessfuly installed wget 3.2 
but that line again came 
python-debianbts 2.7.2 requires pysimplesoap, which is not installed.
and after running social fish i got this
File "SocialFish.py", line 29
    '''.format(RED, END)
      ^
SyntaxError: invalid syntax

**Comment by usama7628674** [comment]
@khawabkashyap Please run the command `pip install wget` and share the pic.I need to know where it's installing it

**Comment by usama7628674** [comment]
@khawabkashyap No install `pip install pysimplesoap`

**Comment by prizoner627** [comment]
after doint this " sudo python -m pip install -U --force-reinstall pip " 
i got this problem .. any sujjestions
#pip install requirements.txt 
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by usama7628674** [comment]
@prizoner627 Update pip using `pip install -U pip`

**Comment by khawabkashyap** [comment]
@usama7628674 
root@localhost:~/SocialFish# python SocialFish.py 
  File "SocialFish.py", line 29
    '''.format(RED, END)
      ^
SyntaxError: invalid syntax
problem still persists..what to do now

**Comment by usama7628674** [comment]
@khawabkashyap Run this way `python2 SocialFish.py` or `python2.7 SocialFish.py`

**Comment by A1S0N** [comment]
fixed in new version

**Comment by usama7628674** [comment]
@dash2x Please raise the issue [here](https://github.com/An0nUD4Y/SocialFish)

**Comment by Arathis6k8** [comment]
when i run python3 SocialFish.py I get
Traceback (most recent call last):
File "SocialFish.py", line 2, in <module>
 from flask import Flask, request, render_template, jsonify, redirect, g, flash
ModuleNotFoundError: No module named 'flask'

What to do next 
installed huepy and wget successfully
![Screenshot from 2019-03-15 16-04-26](https://user-images.githubusercontent.com/48555337/54426034-d9407200-473c-11e9-9279-54986d0f7d46.png)

**Comment by itz-8infinite** [comment]
> when i run python3 SocialFish.py I get
> Traceback (most recent call last):
> File "SocialFish.py", line 2, in
> from flask import Flask, request, render_template, jsonify, redirect, g, flash
> ModuleNotFoundError: No module named 'flask'
> 
> What to do next
> installed huepy and wget successfully
> ![Screenshot from 2019-03-15 16-04-26](https://user-images.githubusercontent.com/48555337/54426034-d9407200-473c-11e9-9279-54986d0f7d46.png)

yeh you can solve these error by installing all the dependencies for Socialfish
use command
-cd Socialfish
-pip install -r requirements.txt
(thinking you have installed python-pip earlier)

and then re-run

**Comment by skandar007** [comment]
aidez-moi....
s'il vous plaît
python2 SocialFish.py
Traceback (most recent call last):
  File "SocialFish.py", line 2, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
ImportError: No module named flask
$ cd SocialFish.py

**Comment by ayeubz** [comment]
Because your not runming as root
