### ISSUE TITLE
> What is the username & password for Social fish its not coming.....plz help me![Screenshot_20210415-151430.jpg](https://user-images.githubusercontent.com/61221663/114849366-4b448300-9dfd-11eb-919b-2138d2b6ff0e.jpg)

### ISSUE THREAD

**Issue by saedee** [UndeadSec/SocialFish#292]
> What is the username & password for Social fish its not coming.....plz help me![Screenshot_20210415-151430.jpg](https://user-images.githubusercontent.com/61221663/114849366-4b448300-9dfd-11eb-919b-2138d2b6ff0e.jpg)
> 
> What should I do...I'm using in termux in mobile

_Originally posted by @saedee_f1 in https://github.com/UndeadSec/SocialFish/issues/280#issuecomment-853349051_

**Comment by busigor0110** [comment]
python3 SocislFish.py cyberpunk pasword123

**Comment by Koobecaf123** [comment]
Fuck
