### ISSUE TITLE
Attack Link Not Working !URGENT!

### ISSUE THREAD

**Issue by s7612f** [UndeadSec/SocialFish#296]
Hi guys.. see if you can help me out:

I have had no installation problems, but the attack link does not work. I have https://www.instagram.com/accounts/login/ as the clone and https://www.google.com/ as the redirect. When I open 0.0.0.0:5000 in Kali, I get the greyed-out instagram logo, and on twitter login, I get 'login/' all down the page. Also, when I open it in Safari (I'm using a Mac), it just can't connect to the page. I have tried using my 192. IP, but that didn't load either.

Steps to reproduce the behaviour:
1. Go to your http://0.0.0.0:5000/creds/ page 
2. In 'clone': instagram.com/accounts/login/
3. In 'Redirection': https://www.google.com/
4. Click the attack URL
5. Find error

The attack link doesn't ever work, wether it doesn't load the page, or it doesn't load the clone page.

I expected it to load the cloned page

 - OS: macOS
 - Browser KALI- Firefox and macOS-Safari
 - Version BigSur/LatestKali

<img width="1425" alt="Screenshot 2021-08-22 at 19 58 26" src="https://user-images.githubusercontent.com/75951407/130366853-67f9600c-dced-4790-b199-11a947ce1b2a.png">

**Comment by Deadpool2000** [comment]
Hello s7612f,

Due to some security reasons, Instagram doesn't allow to clone login and other pages to prevent phishing attacks.

Hope you will understand.

**Comment by Foxemolie** [comment]
i have an issue that when goin on the link "http://0.0.0.0:5000/creds/" it says internal server error  The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." it wont let me see the options like the attack options i dont know how to fix it prob the link got banned or smth pls help
