### ISSUE TITLE
HOW TO SET UP AN VECTOR ATTACK PLS

### ISSUE THREAD

**Issue by P-SamiDev-Y** [UndeadSec/SocialFish#299]
Hey there! I have a problem, when I go to xxx.xxx.x.xxx:5000, I have this thing showing up :

![image](https://user-images.githubusercontent.com/73015114/137629094-008c3955-f595-4572-aeec-40a118c7b6f0.png)

So I'm pretty sure I need to setup a vector attack, I just don't know how to :'(. Any help would be welcome.

**Comment by Krizsan0596** [comment]
You have to head to xxx.xxx.xxx.xxx:5000/neptune to set up an attack vector. The address without /neptune is where you will see your fake site.

**Comment by SamiDevLikesCoding** [comment]
Omg thank you so much it worked!! (sorry btw if it was a dumb question i'm new heh :') ) Have a good day mate!

**Comment by Krizsan0596** [comment]
You're welcome! Make sure you read the docs, I believe this was also in there...
