### ISSUE TITLE
Safari Cant Connect to the Server

### ISSUE THREAD

**Issue by ernevvv** [UndeadSec/SocialFish#302]
Hi you think you can help me with this issue with social fish?
I downloaded SocialFish in the search of working Phishing tools. Im having a similar problem that I used to have(still have) with Blackeye-im. After I create the link on blackeye-im its an ngrok link and in SocialFish its http://0.0.0.0:5000. When I open both of the links on my own browser(Linux Firefox)  it works fine. When I open the links on other browsers(for example safari on IOS and in Mac OS, even tried Firefox on Mac OS) I receive this type of message:
http://0.0.0.0:5000

{                                                                                                                                    Faild to open page 

                                            Safari cant Connect to Server
Safari can't open page"0.0.0.0:5000" Because Safari cant connect to server "0.0.0.0".}

Any Suggestions?Solutions?other phising tools that work
is it a problem with my network setup?

**Comment by Frankie234valid** [comment]
Same bro
