### ISSUE TITLE
Can i contribute to develop socialfish ?

### ISSUE THREAD

**Issue by An0nUD4Y** [UndeadSec/SocialFish#31]
Hi Undeadsec,

I want to develop the tools socialfish ,,,,,, can i do that....

One of updated socialfish is available at 
https://github.com/An0nUD4Y/SocialFish/﻿

**Comment by An0nUD4Y** [comment]
try this one.... https://github.com/An0nUD4Y/SocialFish

**Comment by A1S0N** [comment]
Hello @An0nUD4Y, Please send me a pull request :D
