### ISSUE TITLE
the http://0.0.0.0:5000 url doesnt work 

### ISSUE THREAD

**Issue by MinntFM** [UndeadSec/SocialFish#314]
the http://0.0.0.0:5000 url doesnt work it just says cant reach site is there another way to get to the phishing link ( the login area)

**Comment by franklintimoteo** [comment]
1.Try using the ip of your host SocialFish. 
2.Try accessing from the same network

**Comment by rimaxa** [comment]
Vat

در تاریخ جمعه ۲۲ آوریل ۲۰۲۲،‏ ۰۳:۲۱ Franklin Timóteo <
***@***.***> نوشت:
