### ISSUE TITLE
pls i keep on getting this after trying to add my usernam and password

### ISSUE THREAD

**Issue by Cesarsilva000** [UndeadSec/SocialFish#317]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**
this is what i get after doing all the instructions
                                                                                                                                                                    
┌──(root㉿kali)-[~/SocialFish]
└─# python3 SocialFish.py  username password
Traceback (most recent call last):
  File "/root/SocialFish/SocialFish.py", line 14, in <module>
    from core.report import generate_unique #>> new line
  File "/root/SocialFish/core/report.py", line 2, in <module>
    from pylatex import Document, PageStyle, Head, Foot, MiniPage, \
  File "/usr/local/lib/python3.9/dist-packages/pylatex/__init__.py", line 8, in <module>
    from .basic import HugeText, NewPage, LineBreak, NewLine, HFill, LargeText, \
  File "/usr/local/lib/python3.9/dist-packages/pylatex/basic.py", line 9, in <module>
    from .base_classes import CommandBase, Environment, ContainerCommand
ValueError: source code string cannot contain null bytes

**Comment by franklintimoteo** [comment]
For some reason it happens on first run. Running a second time does not happen.
I don't know resolve it now.

**Comment by Cesarsilva000** [comment]
Use your actual password and username some people think that social phish
wants you to create a username and password but actually you should use the
password on your device Eg username kali password kali
If you still dont get it contact me on telegram with @CODEXWARRIOR or just
email me thanks
