### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by yHopz** [UndeadSec/SocialFish#318]
When i clone the page, this error appears:

 **405 Method Not Allowed** 
The method is not allowed for the requested URL.

 How can i fix it?

**Comment by franklintimoteo** [comment]
Hello @yHopz 
Which page do you clone?

**Comment by yHopz** [comment]
> Hello @yHopz 
> Which page do you clone?

https://siga.activesoft.com.br/

**Comment by franklintimoteo** [comment]
It seems that the action="/login" field is not set during cloning.
try configure action on form html: 


```
<form class="login-form" method="POST" style="width: 25rem;">
to 
<form class="login-form" action="/login" method="POST" style="width: 25rem;">


```

**Comment by yHopz** [comment]
Didn't worked bro

**Comment by franklintimoteo** [comment]
I tested here and seems to work. Do you go in templates/....?
