### ISSUE TITLE
You have not yet set up an attack vector

### ISSUE THREAD

**Issue by lordloser** [UndeadSec/SocialFish#320]
I did everything but I failed what I needed to do 
![Screenshot_2022-04-24-16-09-10-261_com opera browser](https://user-images.githubusercontent.com/103025191/164978124-211aedfe-52c8-460a-9faf-ce8f60e332d3.jpg)

**Comment by franklintimoteo** [comment]
Go to yourIP:5000/neptune
Add a vector and come back there

**Comment by lordloser** [comment]
OK now I get it thxx
