### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by XytheRoblox** [UndeadSec/SocialFish#321]
I was testing socialfish with my website, but it kept on giving me a 405 error in the console. I am currently using the terminal on MacOs Mojave. 
Screenshots:
<img width="576" alt="Screen Shot 2022-04-30 at 10 10 25 AM" src="https://user-images.githubusercontent.com/72460901/166111239-e4452e56-6fc0-4664-aef7-e304f5ef2c17.png">

The link I was using:
https://keepyousafe.info/clients/login.php

**Comment by franklintimoteo** [comment]
The incorrect action field is set
try change on template

```
<form method="post" action="index.html">
to 
<form method="post" action="/login">
```

```
$ egrep -nH "action=" templates/fake/https-keepyousafe.info/clients/login.php/* 

templates/fake/https-keepyousafe.info/clients/login.php/index.html:12:  <form method="post" action="index.html">

```

#318

**Comment by XytheRoblox** [comment]
on the html code?

**Comment by franklintimoteo** [comment]
> on the html code?

yes. 
file
templates/fake/https-keepyousafe.info/clients/login.php/index.html
line 12
