### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by XytheRoblox** [UndeadSec/SocialFish#322]
I am currently trying to make a SocialFish page for https://roblox.com/login for a prank on my friend.

SocialFish dashboard is working perfectly and it says "Success" when I set the attack vector to this website.

It gives me a page saying "Internal Server Error"

I don't know how to fix this, please help me.

Screenshots: 
<img width="1280" alt="Screen Shot 2022-04-30 at 6 40 55 PM" src="https://user-images.githubusercontent.com/72460901/166126177-c8f1a40f-d2dd-4e8c-be32-3aee5dec9970.png">

<img width="891" alt="Screen Shot 2022-04-30 at 6 38 40 PM" src="https://user-images.githubusercontent.com/72460901/166126174-e6c0697f-7287-4343-9ac2-c09367b2f56b.png">

As was stated above, the site I am using is https://roblox.com/login.

**Comment by franklintimoteo** [comment]
Try to clone again SocialFish repository.

**Comment by XytheRoblox** [comment]
It worked, but now it wont capture credentials

**Comment by franklintimoteo** [comment]
See the bugs: 
#314
#308

**Comment by XytheRoblox** [comment]
How do I use ngrok

**Comment by XytheRoblox** [comment]
how

**Comment by franklintimoteo** [comment]
./ngrok http 5000

**Comment by XytheRoblox** [comment]
ok

**Comment by XytheRoblox** [comment]
and do I put the link to my socialfish page there?

**Comment by franklintimoteo** [comment]
Ngrok is to access your device (fake page) Network nat in the internet.

**Comment by XytheRoblox** [comment]
ok

**Comment by XytheRoblox** [comment]
I used ngrok, but now I am getting this error
<img width="1277" alt="Screen Shot 2022-05-01 at 10 00 16 AM" src="https://user-images.githubusercontent.com/72460901/166151714-82815130-6b6c-4bfc-bbfb-5e2627b9558f.png">

**Comment by XytheRoblox** [comment]
hello?

**Comment by franklintimoteo** [comment]
It looks like roblox can avoid basic cloning with a javascript script. You will have to clone manually or use our custom html.

**Comment by XytheRoblox** [comment]
how
