### ISSUE TITLE
Socialfish doesn't start on 0.0.0.0:5000

### ISSUE THREAD

**Issue by Matt10n3** [UndeadSec/SocialFish#329]
When I start it, it starts on my IP and even it doesn't work.
Please help me.

**Comment by RomanJus** [comment]
Experiencing the same issue right now, wasn't able to find a fix yet.

**Comment by Havenontop** [comment]
i too

**Comment by ghost-kali** [comment]
I too

**Comment by amarildo588** [comment]
tambem estou com mesmo problema

**Comment by throwawaya609** [comment]
same

**Comment by caius12345** [comment]
If you are using windows you have to get into 'kex' and then go to the firefox browser and try again, it won't work on your device browser it has to be on kali, it worked for me

**Comment by Mardiasa** [comment]
me too im using google cloud shell 
how to fix it

**Comment by TrystanScottLambert** [comment]
I think that instructions should say 0.0.0.0:5000/neptune

**Comment by CodedPapaya** [comment]
> When I start it, it starts on my IP and even it doesn't work. Please help me.

I am not so sure if it will work if you build it on a vps server. you can as well try out pmap services.

**Comment by franklintimoteo** [comment]
https://github.com/UndeadSec/SocialFish/issues/353
https://github.com/UndeadSec/SocialFish/issues/324
