### ISSUE TITLE
ModuleNotFoundError: nmap

### ISSUE THREAD

**Issue by AliMark71** [UndeadSec/SocialFish#330]
when I run SocialFish like this: 

sudo python3 SocialFish.py <username> <password>

I get this weird error:

Traceback (most recent call last):
  File "/home/kali/SocialFish/SocialFish.py", line 6, in <module>
    from core.scansf import nScan
  File "/home/kali/SocialFish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'

but the weird thing is that I have python-nmap installed and I can use it in other python files but this one gives me this error.

**Comment by cpena28** [comment]
python3 -m pip install -r requirements.txt it works

**Comment by Keplar22B** [comment]
i have the same issue too, any idea on how to fix it?

**Comment by franklintimoteo** [comment]
Fix with https://github.com/UndeadSec/SocialFish/commit/0006dca62fd0c3483402dc495b3c112c2deed19f

**Comment by Tmalhussain** [comment]
Import the requirements folder.
