### ISSUE TITLE
how to use BeEF with your software?

### ISSUE THREAD

**Issue by danielsuperone** [UndeadSec/SocialFish#331]
**Describe the bug**
First off id like to say, I am not sure if this is a bug, however, my problem is this, i managed to install beef-xss and i am able to run it on my local host and perform different attacks and stuff, however, i don't know how to link beef-xss to SocialFish, these are both great tools and if they work together it would be a really powerful tool. So my question is how do i link beef-xss to SocialFish, before creating a clone page (which works amazingly, great job devs) i press the tick box thing to inject beef-xss and then when i open the newly creates page on 0.0.0.0:5000 i see my cloned web page but when i open the beef control panel it doesn't say that there are any connected hosts... Do i have to port forward some ips? use Ngrok? Any advice would be greatly appreciated.

**To Reproduce**
Start up beef-xss and SocialFish, before cloning the webpage i tick the box to inject beef-xss and clone the web page.

**Expected behavior**
in the beef-xss web page, i should see that the host is connected in online and appears there

**Desktop (please complete the following information):**
 - OS: [KALI]
 - Browser [fire fox (kali default)]
 - Version [LATEST]

**Additional context**
Any help would be really appreciated, also just a quick question, how can i copy the google login page so that i can get the google login credentials, would i need to re-craete the google login page myself? (since when i input the url of the google login it doesn't work as intended, same goes with Instagram, Facebook, etc...)

**Comment by iNoSec2** [comment]
Stop using tool and learn basic networking and coding, basic of JS/PHP for example... Python to automate things and C if you move to evading AV/EDR... What you ask is very basic but you dont have solid foundation and you will Always be dépendent of others tools
