### ISSUE TITLE
FackebookFish - kali linux* send this link to the victim : No link......please help!

### ISSUE THREAD

**Issue by rajk786** [UndeadSec/SocialFish#336]
SocialFish - kali linux* send this link to the victim : No link......please help!

<img width="284" alt="git clone" src="https://user-images.githubusercontent.com/118314281/203731105-ca430b6a-0d59-43ea-9f06-ed8c5f58e55c.png">

**Comment by svistiik** [comment]
Message seve.services on ig

**Comment by Salmanamna** [comment]
Help

**Comment by mustafahashimi** [comment]
how i download this please tell  me ****
