### ISSUE TITLE
"You have not yet set up an attack vector"

### ISSUE THREAD

**Issue by HXCKER69** [UndeadSec/SocialFish#340]
![image](https://user-images.githubusercontent.com/123444909/214418223-eb2487e5-f1d8-4116-995b-71691b2f84b6.png)

**Comment by svistiik** [comment]
message seve.services on instagram for help

**Comment by Nitesh-mint** [comment]
go to http://0.0.0.0:5000/neptune and in the clone box enter the url you want to clone and redirect box should contain the page to be redirected ! that's it
