### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Ahmadking78** [UndeadSec/SocialFish#345]
Hello guys i am facing this issue any ideas ? i have done all the requirements but still dont work ! 
Traceback (most recent call last):
  File "/home/unnamed12/Desktop/SocialFish/SocialFish.py", line 3, in <module>
    from flask import Flask, request, render_template, jsonify, redirect, g, flash
  File "/usr/local/lib/python3.11/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.11/site-packages/jinja2/__init__.py)

**Comment by franklintimoteo** [comment]
Its seems that not all the requirements have been installed.

need to install and to use the same python environment.
