### ISSUE TITLE
Socialfish isn’t recording login credentials

### ISSUE THREAD

**Issue by Corruptbyte** [UndeadSec/SocialFish#347]
I can’t seem to find a fix for this please help!

**Comment by Ahmadking78** [comment]
I have the same problem.

**Comment by Ahmadking78** [comment]
ohhh just fix the problem its working fine for me.

**Comment by Ahmadking78** [comment]
let me know if you need anyhelp.

**Comment by Corruptbyte** [comment]
Yes please how did you fix the issue???

**Comment by Ahmadking78** [comment]
could you explain me more ? when you run the project does it run perfectly. i mean when you run the [SocialFish.py] its working you dont get any error ?

**Comment by Corruptbyte** [comment]
This is the error I get now when trying to open SocialFish

Traceback (most recent call last):
  File "/home/odin/SocialFish/SocialFish.py", line 6, in <module>
    from core.scansf import nScan
  File "/home/odin/SocialFish/core/scansf.py", line 1, in <module>
    import nmap
ModuleNotFoundError: No module named 'nmap'


I have Nmap installed too but error persists.

**Comment by franklintimoteo** [comment]
Look https://github.com/UndeadSec/SocialFish/commit/0006dca62fd0c3483402dc495b3c112c2deed19f
