### ISSUE TITLE
No Matching distribution found for nmap

### ISSUE THREAD

**Issue by pyx9999** [UndeadSec/SocialFish#349]
I am a windows user trying to install SocailFish. I have tried everything. But I cannot get a successful install.

I have installed python-nmap, via pip, and I have nmap for windows (zenmap with ncap), but I keep getting the same error.

" could not find a version that satisfies the requirement nmap"

**Comment by pyx9999** [comment]
NVM. I removed 'nmap' from the requirements.txt and re-ran the install.

**Comment by Oraclewhite** [comment]
uguale problema anche su distro kali linux, nmap installato e funzionante, ma socialfish non lo rileva

**Comment by pyx9999** [comment]
Yeah. I ended up switching back to an Arch distro.
