### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Daz1593** [UndeadSec/SocialFish#350]
When I run the python3 -m pip install -r requirements.txt I just get the following errors

ERROR: Could not find a version that satisfies the requirement nmap (from versions: none)
ERROR: No matching distribution found for nmap

I have checked and nmap is installed and I have installed python-nmap as well. I have even fully reinstalled my VM with a fresh version of Kali Linux and done update && upgrade and I still get the same error

**Comment by YuvrajGupta555** [comment]
You have to reuse and try all program and then run

**Comment by Daz1593** [comment]
> You have to reuse and try all program and then run

Sorry, what do you mean by this?
