### ISSUE TITLE
When I starte it , on my IP doesn't Work.

### ISSUE THREAD

**Issue by Mealonex** [UndeadSec/SocialFish#351]
Before you submit this bug report check that you have ran the required setup correctly. Follow [the steps on the wiki](https://github.com/UndeadSec/SocialFish/wiki/Setting-Up-SocialFish).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by franklintimoteo** [comment]
Look 
https://github.com/UndeadSec/SocialFish/issues/353
https://github.com/UndeadSec/SocialFish/issues/324
