### ISSUE TITLE
When It Start On my IP doesn't Work.

### ISSUE THREAD

**Issue by Mealonex** [UndeadSec/SocialFish#352]
**When I start on my IP doesn't Work it**

**Address does not found**
1. Go to 'Go to site IP does not found'
4. IP: Error.

**Unexpected Error**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Realme 8i
 - OS:  Colour Is.
 - Browser : Chrome 
 - Version : Android 13

**Comment by franklintimoteo** [comment]
https://github.com/UndeadSec/SocialFish/issues/353
https://github.com/UndeadSec/SocialFish/issues/324
