### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement nmap (from versions: none)  

### ISSUE THREAD

**Issue by K1DLYNX** [UndeadSec/SocialFish#354]
ERROR: Could not find a version that satisfies the requirement nmap (from versions: none)                                                                 
ERROR: No matching distribution found for nmap

Please Help, Im running kali linux 2023.2 on VM and come across this error.

**Comment by franklintimoteo** [comment]
https://github.com/UndeadSec/SocialFish/commit/0006dca62fd0c3483402dc495b3c112c2deed19f
