### ISSUE TITLE
no modules name

### ISSUE THREAD

**Issue by NotAHackerFR** [UndeadSec/SocialFish#357]
hey guys im new to this when i try to run it with /python SocialFish.py i get an error that says no module named core what do i do now ? some one can help me  here or on Discord: ihatethematrix

**Comment by franklintimoteo** [comment]
Hello 
Try 
python SocialFish.py

**Comment by NotAHackerFR** [comment]
Hey thanks! 
im new to this maybe ur more experienced with this could you add me on discord or anything and explain me how to make it work please ? my discord is ihatethematrix

**Comment by NotAHackerFR** [comment]
hey thanks! maybe u could add me on discord and could explain me how to bring it to work would be super helpful my discord is : ihatethematrix

**Comment by franklintimoteo** [comment]
did you manage to solve it?

**Comment by NotAHackerFR** [comment]
Yes but i would be very greateful if u could show me how to get everything up like how do i start to crack the password ?
