### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by naimurhossain** [UndeadSec/SocialFish#362]
Traceback (most recent call last):
  File "/home/naim2point0/SocialFish/SocialFish.py", line 19, in <module>
    import flask_login
  File "/usr/local/lib/python3.11/dist-packages/flask_login/__init__.py", line 15, in <module>
    from .login_manager import LoginManager
  File "/usr/local/lib/python3.11/dist-packages/flask_login/login_manager.py", line 12, in <module>
    from flask import (_request_ctx_stack, abort, current_app, flash, redirect,
ImportError: cannot import name '_request_ctx_stack' from 'flask' (/usr/local/lib/python3.11/dist-packages/flask/__init__.py)

**Comment by seveservices** [comment]
Dm [seve.services](https://www.instagram.com/seve.services/) on instagram we can help you out

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)

**Comment by anonymboy46** [comment]
> Traceback (most recent call last): File "/home/naim2point0/SocialFish/SocialFish.py", line 19, in import flask_login File "/usr/local/lib/python3.11/dist-packages/flask_login/**init**.py", line 15, in from .login_manager import LoginManager File "/usr/local/lib/python3.11/dist-packages/flask_login/login_manager.py", line 12, in from flask import (_request_ctx_stack, abort, current_app, flash, redirect, ImportError: cannot import name '_request_ctx_stack' from 'flask' (/usr/local/lib/python3.11/dist-packages/flask/**init**.py)

bro me to that boolshit i tryd with python/python3/sudo/./__init__.py/sudo__init_.py/SocialFish.py/.SocialFish.py
