### ISSUE TITLE
Have you gotten help because i will like to know as well

### ISSUE THREAD

**Issue by Adjeee3** [UndeadSec/SocialFish#365]
Have you gotten help because i will like to know as well

_Originally posted by @kcash07 in https://github.com/UndeadSec/SocialFish/issues/356#issuecomment-1712750750_
            Can I ask something

**Comment by kcash07** [comment]
Yes ask

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
