### ISSUE TITLE
Issue when to run it!! Help me, thanks.

### ISSUE THREAD

**Issue by vinzsp** [UndeadSec/SocialFish#366]
Traceback (most recent call last):
  File "/home/Jan/tools/SocialFish/SocialFish.py", line 14, in <module>
    from core.report import generate_unique #>> new line
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Jan/tools/SocialFish/core/report.py", line 2, in <module>
    from pylatex import Document, PageStyle, Head, Foot, MiniPage, \
ModuleNotFoundError: No module named 'pylatex'

**Comment by newtothisfornow** [comment]
im new to phishing and couldnt find a community so i made one on discord add me at usertenthousand or join the server here https://discord.gg/REujkWET

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
