### ISSUE TITLE
Kali nethunter terminal no title problem during install chroot

### ISSUE THREAD

**Issue by narayanchandrakar** [UndeadSec/SocialFish#37]
I have Nexus 5 device and I installed Kali nethunter in my device but I want to install full chroot but the terminal show no title and then automatically    close
![screenshot_2018-04-28-10-34-56-458_com offsec nethunter](https://user-images.githubusercontent.com/37969085/39392242-32e40732-4ad0-11e8-9547-b82ef36c9f84.png)

When touch the install & update it show no title and then close

Please help me

**Comment by A1S0N** [comment]
https://github.com/offensive-security/kali-nethunter
