### ISSUE TITLE
I cant download a tool

### ISSUE THREAD

**Issue by MirasakaDrakon** [UndeadSec/SocialFish#377]
I cant download it in termux without root
![Screenshot_20241110-191327_Termux](https://github.com/user-attachments/assets/c90cc422-af31-4424-8f09-b012193cca53)

**Comment by franklintimoteo** [comment]
try 
wget https://github.com/UndeadSec/SocialFish.git

**Comment by MirasakaDrakon** [comment]
> попробуйте wget https://github.com/UndeadSec/SocialFish.git

"No such file or directory"

**Comment by franklintimoteo** [comment]
git config --global core.compression 9
git clone https://github.com/UndeadSec/SocialFish.git

https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed
