### ISSUE TITLE
Request: site  cloner 

### ISSUE THREAD

**Issue by Darkcast** [UndeadSec/SocialFish#38]
It would be cool if you could add a site cloner that would generate the phishing page.
Or can you add a quick wiki on how to create them

**Comment by An0nUD4Y** [comment]
https://github.com/An0nUD4Y/SocialFish try this

**Comment by Darkcast** [comment]
They don't have a site cloner

**Comment by usama7628674** [comment]
@Darkcast Site cloner is useless now cuz you can't capture credentials if username and password fields are not on the same page just like in social engineering toolkit(set).Many sites are now accepting username and password on different pages lime yahoo,live etc

**Comment by Darkcast** [comment]
yes I totally understand that, but if you can get a cloner it would be simple just to mod the html to capture the credentials, right now I am using bootstrap to mimic the sites I want to do pen-testing campaigns. but I do understand that would be some extra coding on your end so it was just a suggestion. btw I made a apple login if your interested

**Comment by usama7628674** [comment]
@Darkcast Yes sure just submit your PR [here](https://github.com/An0nUD4Y/SocialFish).
