### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by willgordge** [UndeadSec/SocialFish#39]
when the ngrok url loads for facebook, it only loads a basic html page. process.php is working, just no css

**Comment by usama7628674** [comment]
@willgordge Yeah links for css changed.Please use the following repo as I added new phishing pages and live info about victim like victim public ip etc.
https://github.com/An0nUD4Y/SocialFish

**Comment by A1S0N** [comment]
New update coming in this week.

**Comment by A1S0N** [comment]
fixed
