### ISSUE TITLE
CSS is not Working in Facebook Login Pages

### ISSUE THREAD

**Issue by prizoner627** [UndeadSec/SocialFish#41]
When i open the ngrok link .. these two pages' css won't load properly

 [1] Standard Page Phishing
 [2] Advanced Phishing(poll_mode/login_with)

**Comment by prizoner627** [comment]
[1] Standard Page Phishing
![screenshot from 2018-06-16 15-00-49](https://user-images.githubusercontent.com/40322690/41501624-188b15f2-7176-11e8-9cba-680bf7bdef25.png)

 [2] Advanced Phishing(poll_mode/login_with)
![screenshot from 2018-06-16 15-01-54](https://user-images.githubusercontent.com/40322690/41501632-3f06d14e-7176-11e8-8ebb-84c465bd90a5.png)

but others work 
Wordpress
![screenshot from 2018-06-16 15-03-21](https://user-images.githubusercontent.com/40322690/41501649-70d6eb00-7176-11e8-8684-81240e2675a8.png)

**Comment by usama7628674** [comment]
@prizoner627 The first page does have problem of not loading css properly.The more advanced socialfish with a lots of new pages is available.All the phishing pages are mobile compatible as well.The second page is fine.It's just work that way.
https://github.com/An0nUD4Y/SocialFish

**Comment by itachi7777** [comment]
I cant git clone back the same site which i cloned from the social fish . It stops and fails at 26%

**Comment by usama7628674** [comment]
@itachi7777 I don't understand what you're saying.

**Comment by TaKeO90** [comment]
they didn't fix the css issue Yet ??

**Comment by A1S0N** [comment]
Hello, yes i saw that, thanks. New update coming in this week.

**Comment by TaKeO90** [comment]
Thank you !! Waiting for the new update !

**Comment by A1S0N** [comment]
Fixes
