### ISSUE TITLE
CSS is not Working in Facebook Login Pages. Why?

### ISSUE THREAD

**Issue by omern18** [UndeadSec/SocialFish#42]
When i open the ngrok link... these two pages' css won't load properly

[1] Standard Page Phishing
[2] Advanced Phishing(poll_mode/login_with)

![41501624-188b15f2-7176-11e8-9cba-680bf7bdef25](https://user-images.githubusercontent.com/34520966/42054683-b4b48d36-7b1d-11e8-9aa7-f9adb1fe8db1.png)
![41501632-3f06d14e-7176-11e8-8ebb-84c465bd90a5](https://user-images.githubusercontent.com/34520966/42054684-b4d75924-7b1d-11e8-8370-bd918498a092.png)

But others work.
Why?

**Comment by A1S0N** [comment]
Hello, yes i saw that, thanks. New update coming in this week.

**Comment by A1S0N** [comment]
Fixed in new version. :D
