### ISSUE TITLE
problem with the new version of SocialFish

### ISSUE THREAD

**Issue by steve01101** [UndeadSec/SocialFish#44]
```
# python3 SocialFish.py 
Traceback (most recent call last):
File "SocialFish.py", line 22, in <module>
from core.view import *
File "/home/steve/Scrivania/SocialFish-master/core/view.py", line 14, in <module>
from huepy import *
ModuleNotFoundError: No module named 'huepy'
```

**Comment by A1S0N** [comment]
sudo pip3 install huepy

**Comment by steve01101** [comment]
thanks

**Comment by steve01101** [comment]
but now there is another problem, when I start Social Fish, it shows me the Apache2 Ubuntu Default Page.

**Comment by steve01101** [comment]
there is another problem, in the file index.html of instagram, opening it, see the instagram's logo, but when i start the program and i open the site, i can't see the logo.

**Comment by SubaruBacon** [comment]
# python3 SocialFish.py 
Traceback (most recent call last):
File "SocialFish.py", line 22, in <module>
from core.view import *
File "/home/steve/Scrivania/SocialFish-master/core/view.py", line 14, in <module>
from huepy import *
ModuleNotFoundError: No module named 'huepy'
I run the command
sudo pip3 install huepy
and i got as a reply 
Requirements already satisfied huepy in /usr/local/lib/python33.6/dist-packages
But i Still get the same output when i try to run SocialFish
please help!!!

**Comment by A1S0N** [comment]
@SubaruBacon Are you running python3?

**Comment by SubaruBacon** [comment]
Yes I have downloaded the latest version of python

**Comment by An0nUD4Y** [comment]
Try this one : https://github.com/An0nUD4Y/SocialFish

**Comment by steve01101** [comment]
hi. I closed the terminal before seeing the password, can I see it in another way?

**Comment by A1S0N** [comment]
@steve01101 Of course, see in Logs/

**Comment by steve01101** [comment]
where? @A1S0N

**Comment by keethesh** [comment]
> where? @A1S0N
SocialFish > Logs

**Comment by dk4fri** [comment]
Hi This don't word with my linux

**Comment by zski01** [comment]
Yes

**Comment by Mr-idra** [comment]
but you can run on termux
P.s sorry for my english i'm russian

**Comment by dk4fri** [comment]
No problem.
Thanks

**Comment by kinghacking48** [comment]
no module nmap?
