### ISSUE TITLE
Instagram module isn't working. Blank page is loaded.

### ISSUE THREAD

**Issue by BobNiko** [UndeadSec/SocialFish#47]
STR:
Run socialfish
Choose 5>Instagram
Wait for the link
Follow the link
AR: Blank page is displayed to the victim
ER: Fake instagram login page displayed
See the screenshot. 
http://prntscr.com/k84rgt

Thanks in advance!

**Comment by An0nUD4Y** [comment]
Try this one : https://github.com/An0nUD4Y/SocialFish

**Comment by A1S0N** [comment]
@BobNiko Fixed
