### ISSUE TITLE
Issue with parrot sec OS 

### ISSUE THREAD

**Issue by SheesAli** [UndeadSec/SocialFish#5]
When I am pressing 2 for " Advanced Phishing(poll_mode/login_with) " It is showing following error:

Traceback (most recent call last):
  File "SocialFish.py", line 184, in <module>
    runNgrok()
  File "SocialFish.py", line 175, in runNgrok
    print('\n {0}[{1}*{0}]{1} Ngrok URL: {2}' + url.readlines()[0] + '{1}').format(CYAN, END, GREEN)
IndexError: list index out of range

**Comment by SheesAli** [comment]
It is working fine in kali linux, shows erros in parrot sec os

**Comment by A1S0N** [comment]
Please delete your local folder and clone again. The error must be fixed now.

**Comment by SheesAli** [comment]
Still showing this error..

**Comment by SheesAli** [comment]
Still showing the same problem

**Comment by SheesAli** [comment]
![screenshot at 2018-02-04 00-26-31](https://user-images.githubusercontent.com/13631433/35771738-5d3ac7f0-0953-11e8-89b9-a5d37afc12ab.png)

**Comment by A1S0N** [comment]
Please follow these steps:
1) Open your terminal, type "python" and press enter.
2) type "from platform import platfom" and press enter.
3) type "print platform()" and press enter.

Show me the output.

**Comment by SheesAli** [comment]
![screenshot at 2018-02-04 15-31-25](https://user-images.githubusercontent.com/13631433/35777564-ce093a9c-09d1-11e8-8665-638b345c0d9f.png)
