### ISSUE TITLE
problem with the new version of SocialFish

### ISSUE THREAD

**Issue by steve01101** [UndeadSec/SocialFish#60]
hi, when I start Social Fish and then I open the link it does not show me the login screen, only with instgram's login, maybe i'm wrong but i hope that you can help me.

**Comment by An0nUD4Y** [comment]
Hey @steve01101 try this one https://github.com/An0nUD4Y/SocialFish

**Comment by steve01101** [comment]
thanks @An0nUD4Y

**Comment by A1S0N** [comment]
Fixed
