### ISSUE TITLE
Problem With The Instagram Page....

### ISSUE THREAD

**Issue by ShaktisinhJadeja** [UndeadSec/SocialFish#62]
please solve this issue in instagram page.. it's shows blank page only

**Comment by An0nUD4Y** [comment]
Hey dude try this repo ... _: https://github.com/An0nUD4Y/SocialFish

Or wait for next PR

**Comment by A1S0N** [comment]
@ShaktisinhJadeja Fixed

**Comment by Kowshiksriraman** [comment]
I get the same problem

**Comment by shujistu** [comment]
its dec 2019 and still whenever i try to put instagram.com in the link, all i get is the white page with instagram logo, is there a solution for this?
