### ISSUE TITLE
i got a problem python3-pip

### ISSUE THREAD

**Issue by ganeshmandavalli** [UndeadSec/SocialFish#63]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip

**Comment by IWantToBeGod** [comment]
sudo apt-get update

**Comment by ganeshmandavalli** [comment]
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1122: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by ganeshmandavalli** [comment]
sudo apt install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ganeshmandavalli** [comment]
udo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip

**Comment by IWantToBeGod** [comment]
Oh, try this -> sudo apt-get update && sudo apt-get install python-pip
