### ISSUE TITLE
Instagram loading Page issue

### ISSUE THREAD

**Issue by Mo95ze** [UndeadSec/SocialFish#67]
Hi sir,
There is an issue of opening the link which is related to Instagram page, once I put the link in the browser the page dose not show even though there is no issue with the internet.

**Comment by A1S0N** [comment]
![screenshot_2018-09-09_21-43-30](https://user-images.githubusercontent.com/33207993/45270982-71e9f280-b479-11e8-9696-25a97d586c24.png)
