### ISSUE TITLE
add new options 

### ISSUE THREAD

**Issue by blackcraw** [UndeadSec/SocialFish#7]
Dear developer 
you had done very good  job wish for u all best .i would like to suggest if you can add twitter and joomla 
if you dont mind thank you all best

**Comment by A1S0N** [comment]
Twitter's ready. Joomla coming soon. :D

**Comment by blackcraw** [comment]
thank you good luck for next i mean (ppl) :D

**Comment by vinod3070** [comment]
Hello, Can we have an update please, just like SET tool to enter our own target. please

**Comment by ming123245** [comment]
please add to the list VK ***vk.com***
