### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by sploitable868** [UndeadSec/SocialFish#73]
The connection to https://xxxxx.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:1449.

Make sure that a web service is running on localhost:1449 and that it is a valid address.

The error encountered was: dial tcp [::1]:1449: getsockopt: connection refused

Works fine for a while, added a bitly redirect link and it just crashes after using the redirect link, any ideas?

**Comment by A1S0N** [comment]
verify your network

**Comment by sachin742** [comment]
I am exactly having the same problem,someone having the solution pleas help your brother.
Thanks
