### ISSUE TITLE
Facebook Site Display Bad 

### ISSUE THREAD

**Issue by Liel4494** [UndeadSec/SocialFish#75]
when i choose the facebook option this is what i see:

![default](https://user-images.githubusercontent.com/43603550/46071077-eade8f00-c187-11e8-990d-1dbb03b3e423.JPG)

**Comment by ApatheticEuphoria** [comment]
Same

**Comment by raidenhacker** [comment]
me too

**Comment by aresthunder1** [comment]
Me too

**Comment by Elektro090PL** [comment]
me too, pls help

**Comment by Liel4494** [comment]
why i dont get any help? please!!

**Comment by SoyDiego** [comment]
Same here!

**Comment by xseth** [comment]
Same issue

**Comment by An0nUD4Y** [comment]
@Liel4494  You can try [this project](https://github.com/An0nUD4Y/SocialFish)
INSPIRED FROM UNDEAD SEC TEAM
THANKS TO UNDEADSEC - FOR SUCH A GREAT TOOL

**Comment by Liel4494** [comment]
the project in the link have the same issue

**Comment by A1S0N** [comment]
Updated!

**Comment by sploitable868** [comment]
Hi, the mobile site display is off now.
