### ISSUE TITLE
Does social fish working on public network?

### ISSUE THREAD

**Issue by evanhuck** [UndeadSec/SocialFish#79]
It delayed always and doesn't work when I try to make a new Mission it says :( [*] google module loaded. Building site...)

And I stay waiting, and finally nothing happened..

I think it doesn't work with public network , does it?

**Comment by An0nUD4Y** [comment]
You Can Try this one..... https://github.com/An0nUD4Y/SocialFish

This is also a Project got inspired from UndeadSec Team,

THANKS TO UNDEADSEC TEAM ....

**Comment by A1S0N** [comment]
Updated
