### ISSUE TITLE
dont install it

### ISSUE THREAD

**Issue by azamet90** [UndeadSec/SocialFish#81]
it is not working it cant even detect my real pip version and it is givind network error all the time

**Comment by keethesh** [comment]
The "issues" category is meant to help devs find errors, not to review the project. So it must be objective, and not subjective.

**Comment by An0nUD4Y** [comment]
@azamet90  You Can Try this one..... https://github.com/An0nUD4Y/SocialFish

This is also a Project got inspired from UndeadSec Team, 

THANKS TO UNDEADSEC TEAM ....

**Comment by A1S0N** [comment]
Updated!
