### ISSUE TITLE
Facebook page looks like shit

### ISSUE THREAD

**Issue by Franchium** [UndeadSec/SocialFish#87]
Its not about low internet speed i think, i try to another phone and network its just looks like that. 

![img_20181204_134814-1](https://user-images.githubusercontent.com/41231953/49423877-c3f89680-f790-11e8-8659-9433d0d41447.png)

**Comment by LordFaggot** [comment]
Try weeman with ngrok it looks a lot better

**Comment by usama7628674** [comment]
@Franchium Try here[](https://github.com/DarkSecDevelopers/HiddenEye)

**Comment by usama7628674** [comment]
@Franchium No you don't need to just use git clone method.Ex
`git clone https://github.com/UndeadSec/SocialFish.git`
`cd SocialFish`
`python SocialFish.py`

You can run this way as well.
