### ISSUE TITLE
VK page

### ISSUE THREAD

**Issue by torerobo** [UndeadSec/SocialFish#88]
1. VK (vk.com, m.vk.com) page looks wrong on a mobile device! 
2. Is it possible to add to VK m.vk.com?
3. Add social network ok.ru

**Comment by kalibri232** [comment]
I fixed problems with vk. Can I help you or send a corrected version of the tool?

**Comment by Lopezflorencerodriguez** [comment]
How can we proceed ?? Tell me the benefit ,? Tell me the cost ,? Apart from
that do you have a means of reaching out to client means ??? Thanks allot I
do appreciate your email,
.

**Comment by kalibri232** [comment]
I don't think it's worth the money, I just wanted to help you because I really like your product

**Comment by kalibri232** [comment]
you can contact me in the telegram @kalibri2323

**Comment by kalibri232** [comment]
You can also contact me romanscvores@gmail.com

**Comment by dimkop** [comment]
@kalibri232 Hello, how can I contact you?

**Comment by dimkop** [comment]
@kalibri232 can you send me your site? I'll be very grateful
