### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by argtje99** [UndeadSec/SocialFish#91]
Hi guys, I get this error when i try to run SocialFish from my Oneplus One Nethunter.

Traceback (most recent call last):                            File "SocialFish.py", line 67, in <module>                    main()
  File "SocialFish.py", line 42, in main
    head()                                                    File "/root/SocialFish/core/view.py", line 59, in head
    ''')))                                                  UnicodeEncodeError: 'ascii' codec can't encode characters in position 285-291: ordinal not in range(128)
root@kali:~/SocialFish#

It seems that the ascii codec can't encode some characters from the SocialFish script. Is there another method to fix this except changing the codec to utf-8. 

Thankyou

**Comment by exigentcircumstance** [comment]
I have the same issue. Anyone have a solution? FYI - running this on Kali / Raspberry Pi 3b+

**Comment by argtje99** [comment]
>           I have the same issue. Anyone have a solution? FYI - running this on Kali / Raspberry Pi 3b+
The error comes up when you use an non amd64 or i386 device. So when you use an ARM devices this error occur. Try running dpkg-reconfigure locales. Then select all locales. After that select en_US.UTF-8.
Then reboot your device and launch terminal. Then use command "locales'' to verify. After that it should work

**Comment by Lopezflorencerodriguez** [comment]
Still can get it right

**Comment by argtje99** [comment]
@lopezflorencerodriguez Follow the above given commands.
