### ISSUE TITLE
Building site... in socialfish and nothing happens..

### ISSUE THREAD

**Issue by nsuie** [UndeadSec/SocialFish#96]
i did all these..
$ cd SocialFish
$ sudo apt-get install python3-pip php unzip -y
$ sudo pip3 install -r requirements.txt
$ python3 SocialFish.py
 and if i select any of the social media sites, it asks me to enter a custom url say ; https://www.facebook.com 
after that building site appears and it loads forever..
Anyone to help, i would be grateful ASAP

**Comment by milannefosters** [comment]
Its because you click at first (1 (Ngrok)) its not working :)
Now its not working at all
