### ISSUE TITLE
This version will not work anymore

### ISSUE THREAD

**Issue by Grey-Hat86** [UndeadSec/SocialFish#97]
Hi Guys,

I've installed the prerequisites. All packages are the latest and up to date, however, when running the Socialfish.py using python3 i am presented with.

"This version will not work anymore. Wait please until the next release. Sorry for the inconvenience.

Any suggestions or do i need to wait for an update?

Thanks
T

**Comment by A1S0N** [comment]
You must to wait for this next version. Give us just one week =D. You will love the new SocialFish!

**Comment by rksharma4185** [comment]
same problem

**Comment by dimkop** [comment]
Understandably, that will not work. web pages as well as servers are completely removed, and in SocialFish.py a command is added that does not allow you to run it

**Comment by modena18** [comment]
Hi, i have the same issue. When do you expect the new version!?
