### ISSUE TITLE
this version will not work anymore 

### ISSUE THREAD

**Issue by rksharma4185** [UndeadSec/SocialFish#98]
please release new version

**Comment by 0l6** [comment]
Same to me 

This version will not work anymore. Wait please until the next release. Sorry for inconvenience.

**Comment by Crewxx** [comment]
Same issues still persist, please have it released

**Comment by philosofonusus** [comment]
yeh same issue

**Comment by mthlvt** [comment]
does anyone knows the reason it doesn't work anymore?
